# -*- coding: utf-8 -*-
"""Contenido del sitio. Edita textos aquí y vuelve a correr build.py."""

CATS = [  # categorías de marcas
    ("videovigilancia", "Videovigilancia"), ("redes", "Redes"), ("computo", "Cómputo"),
    ("energia", "Energía"), ("acceso", "Control de acceso"), ("audio-video", "Audio y video"),
    ("almacenamiento", "Almacenamiento"), ("ciberseguridad", "Ciberseguridad"),
]

BRANDS = [
 dict(name="Hikvision", slug="hikvision", cats="videovigilancia acceso", desc="Fabricante global de videovigilancia, analítica con inteligencia artificial y seguridad electrónica, reconocido por su innovación, calidad y confiabilidad.", lead="Soluciones de videovigilancia con tecnología de clase mundial para proyectos de cualquier escala.", sols=["videovigilancia", "control-de-acceso"]),
 dict(name="Dahua", slug="dahua", cats="videovigilancia acceso", desc="Proveedor de soluciones de videovigilancia y seguridad inteligente con amplio portafolio de cámaras, grabadores y control de acceso.", lead="Videovigilancia inteligente con un portafolio completo para empresas.", sols=["videovigilancia", "control-de-acceso"]),
 dict(name="EZVIZ", slug="ezviz", cats="videovigilancia", desc="Cámaras y dispositivos de seguridad inteligente de fácil instalación, ideales para pequeños negocios y monitoreo desde el celular.", lead="Seguridad inteligente y sencilla de administrar desde tu smartphone.", sols=["videovigilancia"]),
 dict(name="Ubiquiti", slug="ubiquiti", cats="redes videovigilancia", desc="Equipos de red empresarial con administración centralizada: Wi-Fi, switching, enlaces inalámbricos y videovigilancia UniFi.", lead="Redes empresariales administradas de forma centralizada y escalable.", sols=["redes-y-cableado", "videovigilancia"]),
 dict(name="TP-Link", slug="tp-link", cats="redes videovigilancia", desc="Soluciones de conectividad para oficinas y empresas: switches, puntos de acceso, routers y la línea Omada de administración en la nube.", lead="Conectividad confiable con excelente relación costo-beneficio.", sols=["redes-y-cableado"]),
 dict(name="Fortinet", slug="fortinet", cats="ciberseguridad redes", desc="Líder en ciberseguridad con firewalls de nueva generación FortiGate, redes seguras y protección integral de la infraestructura.", lead="Firewalls y ciberseguridad para proteger la red de tu empresa.", sols=["redes-y-cableado"]),
 dict(name="Dell", slug="dell", cats="computo almacenamiento", desc="Computadoras, estaciones de trabajo, servidores y almacenamiento empresarial con soporte y garantía de fabricante.", lead="Cómputo y servidores empresariales con respaldo de fabricante.", sols=["computo-y-equipamiento"]),
 dict(name="HPE Aruba", slug="hpe-aruba", cats="redes", desc="Redes empresariales cableadas e inalámbricas de alto desempeño, con seguridad integrada y administración en la nube.", lead="Redes de alto desempeño para campus y oficinas.", sols=["redes-y-cableado"]),
 dict(name="Lenovo", slug="lenovo", cats="computo", desc="Laptops, equipos de escritorio y estaciones de trabajo para empresas, con líneas ThinkPad y ThinkCentre.", lead="Equipos de cómputo confiables para cada puesto de trabajo.", sols=["computo-y-equipamiento"]),
 dict(name="APC", slug="apc", cats="energia", desc="UPS, protección eléctrica y soluciones de energía de Schneider Electric para mantener la continuidad de la operación.", lead="Respaldo de energía para que tu operación no se detenga.", sols=["energia-y-respaldo"]),
 dict(name="Western Digital", slug="western-digital", cats="almacenamiento videovigilancia", desc="Discos duros y almacenamiento para videovigilancia, NAS y centros de datos, incluidas las líneas WD Purple y WD Red.", lead="Almacenamiento especializado para videovigilancia y datos.", sols=["videovigilancia", "computo-y-equipamiento"]),
 dict(name="Seagate", slug="seagate", cats="almacenamiento videovigilancia", desc="Discos duros para videovigilancia (SkyHawk), NAS (IronWolf) y almacenamiento empresarial de alta capacidad.", lead="Discos de alta capacidad para grabación continua.", sols=["videovigilancia"]),
 dict(name="Kingston", slug="kingston", cats="almacenamiento computo", desc="Memorias RAM, unidades SSD y almacenamiento flash para mejorar el rendimiento de equipos y servidores.", lead="Memorias y SSD para acelerar tus equipos.", sols=["computo-y-equipamiento"]),
 dict(name="Panduit", slug="panduit", cats="redes", desc="Cableado estructurado de cobre y fibra, organización de racks e infraestructura física para centros de datos.", lead="Cableado estructurado e infraestructura física certificada.", sols=["redes-y-cableado"]),
 dict(name="CommScope", slug="commscope", cats="redes", desc="Soluciones de cableado estructurado, fibra óptica y conectividad para edificios y centros de datos.", lead="Conectividad de cobre y fibra para proyectos de largo plazo.", sols=["redes-y-cableado"]),
 dict(name="Rittal", slug="rittal", cats="redes energia", desc="Gabinetes, racks y sistemas de climatización para infraestructura de TI y aplicaciones industriales.", lead="Racks y gabinetes para proteger tu infraestructura.", sols=["redes-y-cableado"]),
 dict(name="CAME", slug="came", cats="acceso", desc="Automatización de accesos: barreras vehiculares, motores para portones, torniquetes y control de acceso.", lead="Automatización y control de accesos vehiculares y peatonales.", sols=["control-de-acceso"]),
 dict(name="Zebra", slug="zebra", cats="computo", desc="Impresoras de etiquetas, lectores de códigos y computadoras móviles para logística, almacén y punto de venta.", lead="Identificación y movilidad para operaciones de almacén.", sols=["computo-y-equipamiento"]),
 dict(name="Logitech", slug="logitech", cats="computo audio-video", desc="Periféricos y soluciones de videoconferencia para salas de juntas y trabajo híbrido.", lead="Videoconferencia y periféricos para equipos de trabajo.", sols=["computo-y-equipamiento"]),
 dict(name="Eaton", slug="eaton", cats="energia", desc="UPS, PDU y administración de energía para centros de datos, oficinas e industria.", lead="Gestión de energía para infraestructura crítica.", sols=["energia-y-respaldo"]),
 dict(name="Samsung", slug="samsung", cats="computo audio-video", desc="Pantallas profesionales, señalización digital, videowalls y monitores para empresas.", lead="Pantallas profesionales y videowalls.", sols=["computo-y-equipamiento"]),
 dict(name="Epson", slug="epson", cats="computo audio-video", desc="Impresoras empresariales, proyectores y escáneres para oficinas y salas de capacitación.", lead="Impresión y proyección para oficinas.", sols=["computo-y-equipamiento"]),
 dict(name="Tripp Lite", slug="tripp-lite", cats="energia redes", desc="UPS, PDU, racks y accesorios de conectividad para centros de datos y oficinas.", lead="Energía y conectividad para centros de datos.", sols=["energia-y-respaldo"]),
 dict(name="CyberPower", slug="cyberpower", cats="energia", desc="UPS y protección eléctrica para equipos de cómputo, redes y videovigilancia.", lead="Protección eléctrica accesible y confiable.", sols=["energia-y-respaldo"]),
 dict(name="Bosch", slug="bosch", cats="videovigilancia acceso audio-video", desc="Seguridad electrónica, detección de intrusión, sistemas de audio y videovigilancia profesional.", lead="Seguridad electrónica y audio profesional.", sols=["videovigilancia", "control-de-acceso"]),
 dict(name="MikroTik", slug="mikrotik", cats="redes", desc="Routers, switches y enlaces inalámbricos con gran flexibilidad de configuración.", lead="Routing y enlaces inalámbricos flexibles.", sols=["redes-y-cableado"]),
 dict(name="Ajax", slug="ajax", cats="acceso videovigilancia", desc="Sistemas de alarma inalámbricos con detección de intrusión y administración desde app.", lead="Alarmas inalámbricas profesionales.", sols=["control-de-acceso", "videovigilancia"]),
 dict(name="CDP", slug="cdp", cats="energia", desc="UPS, reguladores y protección eléctrica para hogares, oficinas y empresas.", lead="Reguladores y UPS para oficinas.", sols=["energia-y-respaldo"]),
]
BRAND = {b["slug"]: b for b in BRANDS}

SOLUTIONS = [
 dict(slug="videovigilancia", name="Videovigilancia", icon="cctv", short="Soluciones de seguridad que te dan tranquilidad en todo momento.",
   card="Seguridad que te da tranquilidad",
   h1=("Videovigilancia para proteger", "lo que más importa"), eyebrow="Videovigilancia · Seguridad · Control",
   lead="Soluciones con cámaras IP, grabadores, monitoreo y analíticos, diseñadas para empresas y proyectos de cualquier tamaño.",
   intro="Soluciones integrales de videovigilancia para empresas, con tecnología de las mejores marcas y el respaldo de un equipo de expertos.",
   script=("Seguridad que", "te da tranquilidad"),
   feats=[("shield", "Protege tu patrimonio"), ("users", "Mayor control operativo"), ("chart", "Previene incidentes"), ("gear", "Tecnología escalable")],
   includes=[("video", "Cámaras IP", "Modelos para interior y exterior con alta resolución, visión nocturna y WDR."),
             ("db", "Grabación y almacenamiento", "Grabadores NVR/DVR, almacenamiento local o en la nube y respaldo de tu información."),
             ("monitor", "Monitoreo remoto", "Accede a tus cámaras en tiempo real desde computadora, tablet o smartphone."),
             ("chart", "Analíticos y control", "Detección de movimiento, cruce de línea y conteo de personas y vehículos.")],
   benefits=[("shield", "Más seguridad", "Disuade incidentes y protege a tu personal, instalaciones y activos."),
             ("clock", "Supervisión en tiempo real", "Mantén el control de tus espacios desde cualquier lugar."),
             ("file", "Evidencia y control", "Grabaciones confiables para investigación y cumplimiento."),
             ("chart", "Escalabilidad", "Crece desde un sitio hasta múltiples sucursales.")],
   apps=["Oficinas corporativas", "Comercios y tiendas", "Bodegas y centros de distribución", "Industria y manufactura", "Residenciales y edificios"],
   brands=["hikvision", "dahua", "ubiquiti", "tp-link", "ajax", "bosch", "western-digital", "seagate"],
   cta=("¿Listo para un entorno más seguro?", "Te ayudamos a diseñar la solución de videovigilancia ideal para tu empresa o proyecto."),
   kw="videovigilancia Monterrey, cámaras de seguridad empresas, CCTV, cámaras IP, NVR"),
 dict(slug="redes-y-cableado", name="Redes y Cableado", icon="network", short="Conectividad confiable y de alto rendimiento para tu operación.",
   card="Conectividad sin límites",
   h1=("Redes y cableado para una", "operación siempre conectada"), eyebrow="Cableado estructurado · Fibra óptica · Wi-Fi",
   lead="Diseñamos e implementamos redes LAN/WLAN, cableado estructurado y fibra óptica con componentes certificados.",
   intro="Infraestructura de red ordenada, documentada y lista para crecer, desde una oficina hasta un campus o centro de datos.",
   script=("Conectividad", "sin límites"),
   feats=[("wifi", "Wi-Fi empresarial"), ("network", "Red ordenada"), ("shield", "Tráfico seguro"), ("trend", "Lista para crecer")],
   includes=[("network", "Cableado estructurado", "Categorías 6 y 6A, certificación de nodos, etiquetado y documentación."),
             ("activity", "Fibra óptica", "Backbones y enlaces entre edificios, fusión y pruebas con reflectómetro."),
             ("wifi", "Redes inalámbricas", "Site survey, puntos de acceso empresariales y roaming sin cortes."),
             ("rack", "Switching y racks", "Switches administrables, gabinetes, organización y energía para tu site.")],
   benefits=[("zap", "Mayor velocidad", "Aprovecha al máximo tus aplicaciones y servicios en la nube."),
             ("refresh", "Menos fallas", "Una red documentada es más fácil de mantener y diagnosticar."),
             ("shield", "Más seguridad", "Segmentación de red, VLAN y firewalls para proteger tu información."),
             ("trend", "Escalabilidad", "Infraestructura preparada para nuevos usuarios y sucursales.")],
   apps=["Oficinas corporativas", "Naves industriales", "Centros de datos", "Escuelas y campus", "Hoteles y hospitales"],
   brands=["panduit", "commscope", "ubiquiti", "tp-link", "hpe-aruba", "fortinet", "mikrotik", "rittal"],
   cta=("¿Tu red necesita orden y velocidad?", "Evaluamos tu infraestructura y te proponemos la mejor arquitectura."),
   kw="cableado estructurado Monterrey, fibra óptica, redes empresariales, wifi empresarial"),
 dict(slug="energia-y-respaldo", name="Energía y Respaldo", icon="zap", short="Tu operación siempre en marcha, con soluciones de energía confiables.",
   card="Tu operación siempre en marcha",
   h1=("Energía y respaldo para que", "tu operación no se detenga"), eyebrow="UPS · Regulación · Protección eléctrica",
   lead="UPS, reguladores, PDU y protección eléctrica dimensionados para tus equipos críticos.",
   intro="Calculamos la carga real de tus equipos para recomendarte el respaldo adecuado, sin quedarte corto ni sobredimensionar.",
   script=("Energía que", "no se detiene"),
   feats=[("battery", "Respaldo continuo"), ("shield", "Equipos protegidos"), ("activity", "Energía estable"), ("refresh", "Continuidad")],
   includes=[("battery", "UPS", "Equipos interactivos y en línea de doble conversión, desde oficina hasta centro de datos."),
             ("activity", "Regulación y protección", "Reguladores, supresores de picos y tierras físicas."),
             ("rack", "Distribución de energía", "PDU básicas, medidas y administrables para racks."),
             ("monitor", "Monitoreo", "Tarjetas de red y software para apagado seguro y alertas.")],
   benefits=[("refresh", "Continuidad operativa", "Tus sistemas siguen funcionando durante apagones y variaciones."),
             ("shield", "Protección de equipos", "Evita daños por picos, sobretensiones y cortes."),
             ("dollar", "Menos pérdidas", "Reduce tiempos muertos y reparaciones costosas."),
             ("bell", "Alertas oportunas", "Recibe avisos antes de que la batería se agote.")],
   apps=["Centros de datos", "Oficinas", "Videovigilancia", "Puntos de venta", "Industria"],
   brands=["apc", "eaton", "tripp-lite", "cyberpower", "cdp", "rittal"],
   cta=("¿Qué pasaría si se va la luz hoy?", "Te ayudamos a calcular el respaldo que realmente necesitas."),
   kw="UPS Monterrey, no break empresarial, respaldo de energía, reguladores"),
 dict(slug="control-de-acceso", name="Control de Acceso", icon="lock", short="Personas, espacios y procesos más seguros y eficientes.",
   card="Personas, espacios y mayor seguridad",
   h1=("Control de acceso para", "espacios más seguros"), eyebrow="Biometría · Tarjetas · Barreras",
   lead="Controla quién entra, cuándo y por dónde con lectores biométricos, tarjetas, torniquetes y barreras vehiculares.",
   intro="Integramos control de acceso, asistencia y videovigilancia para que administres personas y espacios desde una sola plataforma.",
   script=("Acceso seguro,", "operación fluida"),
   feats=[("key", "Accesos controlados"), ("users", "Registro de personal"), ("shield", "Áreas restringidas"), ("card", "Tarjetas y biometría")],
   includes=[("key", "Lectores y biometría", "Huella, rostro, tarjeta o código, en puertas y áreas restringidas."),
             ("walk", "Torniquetes y puertas", "Control peatonal para recepciones, plantas y comedores."),
             ("truck", "Accesos vehiculares", "Barreras, lectura de placas y automatización de portones."),
             ("monitor", "Software y reportes", "Horarios, niveles de acceso y reportes de asistencia.")],
   benefits=[("shield", "Mayor seguridad", "Solo las personas autorizadas acceden a cada área."),
             ("clock", "Control de asistencia", "Registros confiables de entradas y salidas."),
             ("file", "Trazabilidad", "Historial de eventos para auditorías e investigaciones."),
             ("gear", "Integración", "Se conecta con videovigilancia y alarmas.")],
   apps=["Corporativos", "Plantas industriales", "Residenciales", "Estacionamientos", "Escuelas"],
   brands=["hikvision", "dahua", "came", "bosch", "ajax"],
   cta=("¿Quieres saber quién entra a tus instalaciones?", "Diseñamos el sistema de control de acceso adecuado para tu operación."),
   kw="control de acceso Monterrey, biométricos, torniquetes, barreras vehiculares"),
 dict(slug="computo-y-equipamiento", name="Cómputo y Equipamiento", icon="monitor", short="Soluciones para un trabajo más productivo y colaborativo.",
   card="Soluciones para un trabajo más productivo",
   h1=("Cómputo y equipamiento para", "equipos más productivos"), eyebrow="Laptops · Servidores · Videowalls",
   lead="Computadoras, estaciones de trabajo, servidores, pantallas y periféricos para cada puesto de tu empresa.",
   intro="Te ayudamos a elegir el equipo correcto para cada perfil de usuario y a estandarizar tu parque de cómputo.",
   script=("Tecnología para", "trabajar mejor"),
   feats=[("monitor", "Equipos por perfil"), ("server", "Servidores"), ("video", "Salas de juntas"), ("award", "Garantía de fábrica")],
   includes=[("monitor", "Computadoras y laptops", "Equipos de escritorio, laptops y estaciones de trabajo empresariales."),
             ("server", "Servidores y almacenamiento", "Servidores, NAS y almacenamiento para tus aplicaciones y respaldos."),
             ("video", "Pantallas y videowalls", "Pantallas profesionales, señalización digital y salas de videoconferencia."),
             ("printer", "Periféricos e impresión", "Impresoras, etiquetadoras, escáneres y accesorios.")],
   benefits=[("trend", "Más productividad", "Equipos adecuados para cada tarea y usuario."),
             ("award", "Garantía de fabricante", "Productos originales con respaldo oficial."),
             ("layers", "Estandarización", "Un parque de cómputo homogéneo es más fácil de administrar."),
             ("truck", "Entrega en todo México", "Logística para oficinas y sucursales.")],
   apps=["Oficinas", "Salas de juntas", "Centros de monitoreo", "Almacenes", "Escuelas"],
   brands=["dell", "lenovo", "samsung", "logitech", "epson", "zebra", "kingston"],
   cta=("¿Vas a renovar tus equipos?", "Te armamos una propuesta por perfil de usuario y presupuesto."),
   kw="equipo de cómputo empresas Monterrey, laptops empresariales, servidores, videowall"),
]
SOL = {s["slug"]: s for s in SOLUTIONS}

SERVICES = [
 dict(slug="asesoria-especializada", name="Asesoría especializada", icon="user", img="asesoria",
   short="Te orientamos para encontrar la solución adecuada según tus necesidades y presupuesto.",
   h1=("Asesoría especializada", "para encontrar la solución ideal"), eyebrow="Asesoría · Planeación · Tecnología",
   lead="Entendemos las necesidades de tu negocio y te orientamos con la mejor tecnología para que tomes decisiones seguras y alineadas a tus objetivos.",
   sub="Un servicio experto para convertir tus necesidades en soluciones tecnológicas de alto valor.",
   intro="Te acompañamos desde la idea hasta la implementación, analizando tus necesidades, recomendando la tecnología y diseñando una solución a la medida.",
   feats=[("shield", "Proyectos más seguros"), ("users", "Expertos a tu lado"), ("chart", "Tecnología que impulsa"), ("gear", "Resultados reales")],
   includes=[("file-search", "Análisis de necesidades", "Conocemos tu operación, objetivos y desafíos para entender lo que realmente necesitas."),
             ("gear", "Recomendación tecnológica", "Te sugerimos opciones de tecnología, marcas y arquitecturas según tus requerimientos."),
             ("scale", "Evaluación de alternativas", "Comparamos soluciones en costo, funcionalidad y escalabilidad."),
             ("map", "Planeación de solución", "Definimos el plan de implementación, recursos y próximos pasos.")],
   benefits=[("target", "Decisiones fundamentadas", "Con información técnica y análisis experto."),
             ("puzzle", "Solución a la medida", "Tecnología alineada a tus objetivos."),
             ("clock", "Ahorro de tiempo", "Evita pruebas y errores con la guía de especialistas."),
             ("chart", "Mejor inversión", "Maximiza el rendimiento de tu presupuesto.")],
   kw="asesoría tecnológica, consultoría TI Monterrey, diseño de proyectos de seguridad"),
 dict(slug="instalacion", name="Instalación", icon="wrench", img="instalacion",
   short="Implementación física de equipos, cableado e infraestructura tecnológica.",
   h1=("Instalación profesional", "con altos estándares"), eyebrow="Obra · Montaje · Cableado",
   lead="Montamos cámaras, cableado, racks y equipos con técnicos capacitados, cuidando la seguridad, el orden y los tiempos de tu proyecto.",
   sub="Implementación física cuidada, documentada y entregada funcionando.",
   intro="Planeamos la obra contigo, respetamos tus horarios de operación y te entregamos memoria técnica de todo lo instalado.",
   feats=[("shield", "Trabajo seguro"), ("users", "Técnicos certificados"), ("clock", "Tiempos cumplidos"), ("file", "Memoria técnica")],
   includes=[("map", "Levantamiento en sitio", "Visitamos tus instalaciones para definir rutas, alturas y materiales."),
             ("wrench", "Montaje de equipos", "Cámaras, lectores, puntos de acceso, pantallas y racks."),
             ("network", "Canalización y cableado", "Tubería, charola, cableado de cobre y fibra con buenas prácticas."),
             ("file", "Pruebas y entrega", "Certificación, etiquetado y memoria técnica del proyecto.")],
   benefits=[("award", "Calidad de obra", "Instalaciones limpias, ordenadas y duraderas."),
             ("shield", "Seguridad en sitio", "Personal con equipo de protección y protocolos."),
             ("clock", "Menos interrupciones", "Trabajamos en horarios que no afecten tu operación."),
             ("file", "Todo documentado", "Planos y registros para futuros mantenimientos.")],
   kw="instalación de cámaras Monterrey, instalación de cableado estructurado, montaje de racks"),
 dict(slug="configuracion-y-puesta-en-marcha", name="Configuración y puesta en marcha", icon="gear", img="configuracion",
   short="Dejamos tus equipos listos para operar de forma correcta y eficiente.",
   h1=("Configuración y puesta en marcha", "lista para operar"), eyebrow="Configuración · Pruebas · Arranque",
   lead="Configuramos redes, grabadores, firewalls, controles de acceso y servidores con las mejores prácticas de cada fabricante.",
   sub="Tus equipos funcionando desde el primer día, con la configuración correcta.",
   intro="Un equipo bien configurado rinde más y falla menos. Documentamos accesos, respaldos y parámetros para que todo quede bajo control.",
   feats=[("gear", "Buenas prácticas"), ("shield", "Seguridad desde el inicio"), ("activity", "Pruebas completas"), ("file", "Documentación")],
   includes=[("network", "Redes y seguridad", "VLAN, Wi-Fi, firewalls, VPN y políticas de acceso."),
             ("video", "Videovigilancia", "Grabación, analíticos, usuarios y acceso remoto."),
             ("server", "Servidores y equipos", "Sistemas operativos, respaldos, usuarios y actualizaciones."),
             ("activity", "Pruebas de operación", "Validamos cada función contigo antes de entregar.")],
   benefits=[("zap", "Mejor rendimiento", "Equipos ajustados a tu operación real."),
             ("shield", "Más seguridad", "Contraseñas, firmware y accesos bien administrados."),
             ("refresh", "Menos fallas", "Configuraciones estables y probadas."),
             ("file", "Control total", "Documentación clara de accesos y parámetros.")],
   kw="configuración de redes, configuración de NVR, puesta en marcha firewall"),
 dict(slug="soporte-tecnico", name="Soporte técnico", icon="headset", img="soporte",
   short="Atención para resolver dudas, incidencias y requerimientos técnicos.",
   h1=("Soporte técnico", "cuando más lo necesitas"), eyebrow="Remoto · En sitio · Pólizas",
   lead="Resolvemos incidencias de forma remota o en sitio para que tu operación vuelva a la normalidad lo antes posible.",
   sub="Atención técnica cercana, con seguimiento de cada caso.",
   intro="Registramos cada solicitud, te mantenemos informado y damos seguimiento hasta que el problema queda resuelto.",
   feats=[("headset", "Atención directa"), ("clock", "Respuesta ágil"), ("globe", "Remoto o en sitio"), ("file", "Seguimiento")],
   includes=[("headset", "Mesa de ayuda", "Recibimos tus reportes por teléfono, correo o WhatsApp."),
             ("globe", "Soporte remoto", "Diagnóstico y solución a distancia cuando es posible."),
             ("truck", "Visitas en sitio", "Técnicos en tus instalaciones cuando se requiere."),
             ("file", "Pólizas de soporte", "Horas o eventos incluidos con tiempos de respuesta definidos.")],
   benefits=[("clock", "Menos tiempo muerto", "Recupera la operación rápidamente."),
             ("users", "Un solo contacto", "Un equipo que conoce tu infraestructura."),
             ("file", "Historial de casos", "Sabes qué pasó y cómo se resolvió."),
             ("dollar", "Costos previsibles", "Pólizas a la medida de tu operación.")],
   kw="soporte técnico empresas Monterrey, póliza de soporte, soporte redes y CCTV"),
 dict(slug="mantenimiento", name="Mantenimiento", icon="shield", img="mantenimiento",
   short="Servicios preventivos y correctivos para mantener tus soluciones en operación.",
   h1=("Mantenimiento que mantiene", "tu operación en marcha"), eyebrow="Preventivo · Correctivo · Planes",
   lead="Previene fallas, asegura la continuidad de tu operación y maximiza la vida útil de tu infraestructura tecnológica.",
   sub="Equipos siempre funcionando, menos costos inesperados.",
   intro="Programamos visitas periódicas, revisamos cada equipo y te entregamos un reporte con hallazgos y recomendaciones.",
   feats=[("refresh", "Equipos funcionando"), ("dollar", "Menos costos inesperados"), ("clock", "Mayor vida útil"), ("file", "Reportes claros")],
   includes=[("file-search", "Revisión y diagnóstico", "Inspección periódica del estado de cada equipo."),
             ("wrench", "Limpieza y ajuste", "Limpieza, reapriete y alineación de cámaras y equipos."),
             ("refresh", "Actualizaciones", "Firmware y software al día para mayor seguridad."),
             ("file", "Reportes y recomendaciones", "Hallazgos, evidencia y próximos pasos.")],
   benefits=[("shield", "Menor riesgo de fallas", "Detectamos problemas antes de que te detengan."),
             ("refresh", "Operación continua", "Tus sistemas disponibles cuando los necesitas."),
             ("dollar", "Mejor inversión", "Tus equipos duran más y rinden mejor."),
             ("cal", "Planes a la medida", "Frecuencia y alcance según tu operación.")],
   kw="mantenimiento CCTV Monterrey, mantenimiento preventivo redes, mantenimiento UPS"),
 dict(slug="capacitacion", name="Capacitación", icon="users", img="capacitacion",
   short="Acompañamiento para que tu equipo conozca el uso y aprovechamiento de la solución.",
   h1=("Capacitación para aprovechar", "al máximo tu tecnología"), eyebrow="Usuarios · Administradores · Operadores",
   lead="Enseñamos a tu equipo a operar y administrar la solución instalada, con material de apoyo y sesiones prácticas.",
   sub="Formación práctica para usuarios y administradores.",
   intro="Adaptamos cada sesión al perfil de tu equipo: operadores de monitoreo, administradores de red o usuarios finales.",
   feats=[("grad", "Sesiones prácticas"), ("users", "Por perfil"), ("file", "Material de apoyo"), ("headset", "Dudas resueltas")],
   includes=[("grad", "Capacitación de operación", "Uso diario de la plataforma: búsquedas, exportación de video, altas de usuarios."),
             ("gear", "Capacitación de administración", "Configuración, respaldos y buenas prácticas de seguridad."),
             ("file", "Manuales y guías", "Material de consulta adaptado a tu instalación."),
             ("headset", "Seguimiento", "Resolvemos dudas después de la capacitación.")],
   benefits=[("trend", "Más aprovechamiento", "Tu equipo usa todas las funciones que pagaste."),
             ("refresh", "Menos errores", "Operación correcta desde el primer día."),
             ("users", "Autonomía", "Menos dependencia de soporte externo."),
             ("shield", "Más seguridad", "Buenas prácticas en el manejo de accesos.")],
   kw="capacitación videovigilancia, capacitación redes, curso operador CCTV"),
]
SRV = {s["slug"]: s for s in SERVICES}

ARTICLES = [
 dict(slug="como-elegir-la-camara-de-seguridad-ideal", cat="guias", catn="Guía", title="¿Cómo elegir la cámara de seguridad ideal?", date="2026-08-12", read=7,
      desc="Los factores clave para elegir el sistema de videovigilancia que mejor se adapta a tu empresa: lugar, resolución, tipo de cámara y funciones.", img="camara-seguridad", featured=True, full=True),
 dict(slug="ventajas-del-cableado-estructurado", cat="comparativas", catn="Comparativa", title="Ventajas del cableado estructurado en tu empresa", date="2026-08-05", read=6,
      desc="Por qué un cableado bien diseñado mejora el rendimiento, la seguridad y la escalabilidad de tu red.", img="cableado-estructurado", featured=True),
 dict(slug="por-que-necesitas-un-ups", cat="consejos", catn="Consejo técnico", title="¿Por qué necesitas un UPS en tu negocio?", date="2026-07-28", read=5,
      desc="Evita pérdidas, protege tus equipos y garantiza la continuidad de tu operación con un respaldo de energía.", img="ups-negocio", featured=True),
 dict(slug="que-es-poe", cat="tutoriales", catn="Tutorial", title="¿Qué es PoE y cuáles son sus ventajas?", date="2026-08-20", read=5,
      desc="Cómo Power over Ethernet simplifica la instalación de cámaras, teléfonos y puntos de acceso.", img="poe"),
 dict(slug="buenas-practicas-videovigilancia", cat="guias", catn="Guía", title="Buenas prácticas para un sistema de videovigilancia", date="2026-08-15", read=6,
      desc="Consejos clave para maximizar la seguridad y el aprovechamiento de tus cámaras.", img="buenas-practicas-cctv"),
 dict(slug="fibra-optica-vs-cobre", cat="consejos", catn="Consejo técnico", title="Fibra óptica vs. cobre: ¿cuál elegir?", date="2026-08-10", read=6,
      desc="Comparamos ventajas, costos y escenarios de uso para que elijas el medio adecuado.", img="fibra-vs-cobre"),
 dict(slug="control-de-acceso-caso-real", cat="casos", catn="Caso de uso", title="Control de acceso en empresas: un caso real", date="2026-08-02", read=4,
      desc="Cómo un corporativo mejoró su seguridad y eficiencia con control de acceso integrado.", img="caso-control-acceso"),
 dict(slug="nube-vs-almacenamiento-local", cat="comparativas", catn="Comparativa", title="Almacenamiento en la nube vs. almacenamiento local", date="2026-07-28", read=6,
      desc="Diferencias, beneficios y recomendaciones según tu operación.", img="nube-vs-local"),
 dict(slug="tendencias-tecnologicas-2026", cat="novedades", catn="Novedad", title="Tendencias tecnológicas para empresas en 2026", date="2026-07-22", read=5,
      desc="Las tecnologías que están transformando la seguridad y la operación de los negocios.", img="tendencias-2026"),
 dict(slug="camaras-ip-vs-analogicas", cat="comparativas", catn="Comparativa", title="Cámaras IP vs. analógicas: ¿cuál te conviene?", date="2026-07-15", read=6,
      desc="Te ayudamos a entender las diferencias para tomar la mejor decisión.", img="ip-vs-analogicas"),
 dict(slug="como-elegir-un-switch", cat="guias", catn="Guía", title="Cómo elegir un switch para tu red empresarial", date="2026-07-08", read=6,
      desc="Puertos, PoE, capa 2 o 3 y administración: lo que debes revisar antes de comprar.", img="switch-empresarial"),
 dict(slug="nvr-vs-dvr", cat="comparativas", catn="Comparativa", title="Grabadores NVR vs. DVR: ¿cuál elegir?", date="2026-07-01", read=5,
      desc="Conoce las diferencias y aplicaciones de cada tecnología.", img="nvr-vs-dvr"),
]
ART_CATS = [("guias", "Guías", "file", "Aprende paso a paso con nuestros expertos."),
            ("tutoriales", "Tutoriales", "play", "Videos y guías prácticas para tu operación."),
            ("comparativas", "Comparativas", "scale", "Analiza opciones y toma la mejor decisión."),
            ("consejos", "Consejos técnicos", "gear", "Recomendaciones de nuestros especialistas."),
            ("novedades", "Novedades", "bell", "Entérate de las tendencias del sector."),
            ("casos", "Casos de uso", "users", "Historias reales de éxito.")]

MESES = ["", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
MESES_L = ["", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
def fdate(d, long=False):
    y, m, dd = d.split("-")
    return f"{int(dd)} de {MESES_L[int(m)]} de {y}" if long else f"{dd} {MESES[int(m)].upper()} {y}"

FAQ = [
 ("truck", "¿Hacen envíos a toda la República?", "Sí. Enviamos productos a todo México y atendemos proyectos de instalación en distintas ciudades según el alcance."),
 ("box", "¿Puedo solicitar una cotización sin compromiso?", "Por supuesto. Cuéntanos tu necesidad y un asesor te enviará una propuesta sin costo ni compromiso."),
 ("headset", "¿Tienen soporte técnico?", "Sí. Te acompañamos en la implementación y ofrecemos soporte remoto, en sitio y pólizas a la medida."),
 ("clock", "¿En cuánto tiempo responden?", "Respondemos las solicitudes en menos de 24 horas hábiles. Por WhatsApp la atención suele ser inmediata en horario laboral."),
 ("award", "¿Los productos tienen garantía?", "Trabajamos con productos originales de fabricantes líderes, con la garantía oficial de cada marca."),
 ("file", "¿Puedo enviar planos o una lista de materiales?", "Sí. Adjunta tus archivos en el formulario de cotización (PDF, Excel, imágenes o DWG de hasta 10 MB) para agilizar la revisión."),
]
