# -*- coding: utf-8 -*-
"""Contenido del sitio. Edita textos aquí y vuelve a correr build.py."""

CATS = [  # categorías de marcas = las 8 soluciones (los filtros no son excluyentes)
    ("videovigilancia", "Videovigilancia y Seguridad Electrónica"), ("acceso", "Control de Acceso e Identidad"),
    ("redes", "Redes y Telecomunicaciones"), ("cableado", "Cableado, Fibra e Infraestructura"), ("energia", "Energía y Respaldo"),
    ("ciberseguridad", "Ciberseguridad"), ("computo", "Cómputo y TI"), ("audio-video", "Audio, Video y Colaboración"),
]
# Cada categoría corresponde a una solución
CAT_SOL = {"videovigilancia": "videovigilancia", "acceso": "control-de-acceso", "redes": "redes-y-telecomunicaciones",
           "cableado": "cableado-fibra-e-infraestructura", "energia": "energia-y-respaldo", "ciberseguridad": "ciberseguridad",
           "computo": "computo-y-ti", "audio-video": "audio-video-y-colaboracion"}

# Marcas: (nombre, slug, categorías, descripción, frase corta)
# Categorías en orden: solución principal, secundaria y adicional (documento de clasificación de Wiccom).
# La principal define la imagen de la ficha: assets/img/marcas/cat/<categoría>.webp
# El logo va en assets/img/marcas/<slug>.png
_B = [
 ("AccessPRO", "accesspro", "acceso videovigilancia energia", "Lectores, controladores, cerraduras electromagnéticas y accesorios para sistemas de control de acceso comerciales.", "Control de acceso confiable para puertas y áreas restringidas."),
 ("Altronix", "altronix", "energia acceso videovigilancia", "Fuentes de poder, soluciones PoE y distribución de energía para sistemas de videovigilancia y control de acceso.", "Energía confiable para sistemas de seguridad."),
 ("APC", "apc", "energia cableado computo", "UPS, protección eléctrica y soluciones de energía de Schneider Electric para mantener la continuidad de la operación.", "Respaldo de energía para que tu operación no se detenga."),
 ("Apple", "apple", "computo audio-video", "Computadoras, laptops, tabletas y dispositivos para empresas que buscan productividad, diseño y seguridad.", "Equipos para equipos creativos y productivos."),
 ("ASUS", "asus", "computo redes", "Laptops, computadoras de escritorio, monitores y equipos de red para oficinas y usuarios profesionales.", "Cómputo confiable para cada puesto de trabajo."),
 ("Belden", "belden", "cableado redes", "Cable de cobre y fibra óptica, conectividad y soluciones de red para entornos empresariales e industriales.", "Conectividad robusta para entornos exigentes."),
 ("Cambium Networks", "cambium-networks", "redes", "Enlaces inalámbricos punto a punto y punto multipunto, Wi-Fi y switching para conectar sitios y sucursales.", "Conectividad inalámbrica de largo alcance."),
 ("CAME", "came", "acceso videovigilancia", "Automatización de accesos: barreras vehiculares, motores para portones, torniquetes y control de acceso.", "Automatización y control de accesos vehiculares y peatonales."),
 ("CDP", "cdp", "energia computo", "UPS, reguladores y protección eléctrica para hogares, oficinas y empresas.", "Reguladores y UPS para oficinas y comercios."),
 ("Charofil", "charofil", "cableado", "Charola tipo malla y accesorios para la canalización ordenada y segura del cableado.", "Canalización ordenada para tu cableado."),
 ("Check Point", "check-point", "ciberseguridad redes", "Firewalls, protección de red, nube y endpoints para prevenir amenazas en organizaciones de todos los tamaños.", "Prevención de amenazas para tu red."),
 ("Cisco", "cisco", "redes ciberseguridad audio-video", "Switches, routers, Wi-Fi, colaboración y seguridad para redes empresariales de alto desempeño.", "Redes empresariales de clase mundial."),
 ("CommScope", "commscope", "cableado redes", "Soluciones de cableado estructurado, fibra óptica y conectividad para edificios y centros de datos.", "Conectividad de cobre y fibra de alto desempeño."),
 ("Condumex", "condumex", "cableado energia", "Cables eléctricos, de telecomunicaciones y fibra óptica fabricados en México para proyectos de infraestructura.", "Cables confiables para cada instalación."),
 ("CyberPower", "cyberpower", "energia computo", "UPS y protección eléctrica para equipos de cómputo, redes y videovigilancia.", "Protección eléctrica accesible y confiable."),
 ("Dahua", "dahua", "videovigilancia acceso audio-video", "Videovigilancia y seguridad inteligente con amplio portafolio de cámaras, grabadores y control de acceso.", "Videovigilancia inteligente con un portafolio completo."),
 ("Dell", "dell", "computo cableado", "Computadoras, estaciones de trabajo, servidores y almacenamiento empresarial con soporte y garantía de fabricante.", "Cómputo y servidores empresariales con respaldo de fabricante."),
 ("DJI Enterprise", "dji-enterprise", "videovigilancia redes", "Drones profesionales para inspección, seguridad, monitoreo y levantamientos en sitios industriales y obras.", "Drones para inspección y seguridad."),
 ("DSC", "dsc", "videovigilancia acceso", "Paneles de alarma, sensores y comunicadores para detección de intrusión en negocios y residencias.", "Alarmas profesionales para proteger tus instalaciones."),
 ("Eaton", "eaton", "energia cableado computo", "UPS, PDU y administración de energía para centros de datos, oficinas e industria.", "Gestión de energía para infraestructura crítica."),
 ("Elo", "elo", "computo audio-video", "Pantallas táctiles, terminales de punto de venta y kioscos interactivos para comercios y atención al cliente.", "Pantallas táctiles para punto de venta y autoservicio."),
 ("Enson", "enson", "audio-video videovigilancia", "Cables, conectores y accesorios de audio, video y energía para instalaciones y equipos tecnológicos.", "Accesorios y conectividad para tus equipos."),
 ("EPCOM", "epcom", "videovigilancia redes energia", "Portafolio para integradores: cámaras, fuentes de poder, cableado, accesorios y soluciones de energía.", "Accesorios, energía y conectividad para proyectos de seguridad."),
 ("Epson", "epson", "computo audio-video", "Impresoras empresariales, proyectores y escáneres para oficinas, aulas y salas de capacitación.", "Impresión y proyección para oficinas y aulas."),
 ("FAAC", "faac", "acceso videovigilancia", "Automatización de puertas, portones y barreras vehiculares para accesos residenciales, comerciales e industriales.", "Automatización de accesos vehiculares."),
 ("Fanvil", "fanvil", "redes audio-video acceso", "Teléfonos IP, intercomunicadores y dispositivos de comunicación para empresas.", "Telefonía IP e intercomunicación para tu empresa."),
 ("FiberHome", "fiberhome", "redes cableado", "Fibra óptica, equipos de transmisión y soluciones GPON para redes de telecomunicaciones.", "Fibra óptica y redes de acceso."),
 ("Fibrain", "fibrain", "cableado redes", "Cables y componentes de fibra óptica para redes empresariales, centros de datos y telecomunicaciones.", "Fibra óptica para redes de alto desempeño."),
 ("Fluke Networks", "fluke", "cableado redes", "Equipos de prueba y certificación de cableado de cobre y fibra óptica.", "Certificación de cableado con precisión."),
 ("Fortinet", "fortinet", "ciberseguridad redes", "Firewalls de nueva generación FortiGate, redes seguras y protección integral de la infraestructura.", "Firewalls y ciberseguridad para proteger la red de tu empresa."),
 ("Grandstream", "grandstream", "redes audio-video acceso", "Telefonía IP, conmutadores, videoconferencia y redes para pequeñas y medianas empresas.", "Comunicaciones unificadas para tu empresa."),
 ("Hanwha Vision", "hanwha", "videovigilancia", "Cámaras, grabadores y analíticos de video Wisenet para proyectos de videovigilancia profesional.", "Videovigilancia profesional con analítica avanzada."),
 ("HID", "hid", "acceso ciberseguridad", "Lectores, credenciales, impresoras de identificaciones y soluciones de identidad segura.", "Identidad y control de acceso seguro."),
 ("Hikvision", "hikvision", "videovigilancia acceso audio-video", "Fabricante global de videovigilancia, analítica con inteligencia artificial y seguridad electrónica.", "Videovigilancia con tecnología de clase mundial."),
 ("HiRef", "hiref", "cableado energia", "Climatización de precisión para centros de datos, sites y salas de telecomunicaciones.", "Climatización de precisión para tu site."),
 ("nVent Hoffman", "hoffman", "cableado energia", "Gabinetes, envolventes y gestión térmica para proteger equipos eléctricos y electrónicos.", "Gabinetes para proteger tus equipos."),
 ("Honeywell", "honeywell", "videovigilancia acceso cableado", "Seguridad electrónica, detección de intrusión, videovigilancia y control de acceso.", "Seguridad integral para tus instalaciones."),
 ("HP", "hp", "computo", "Computadoras, laptops, impresoras y periféricos para oficinas y empresas.", "Cómputo e impresión para tu empresa."),
 ("HPE Aruba Networking", "hpe-aruba", "redes ciberseguridad", "Redes empresariales cableadas e inalámbricas de alto desempeño, con seguridad integrada y administración en la nube.", "Redes de alto desempeño para campus y oficinas."),
 ("HPE", "hpe", "computo redes cableado", "Servidores, almacenamiento e infraestructura híbrida para centros de datos y aplicaciones críticas.", "Servidores e infraestructura empresarial."),
 ("Huawei", "huawei", "redes computo cableado", "Redes empresariales, Wi-Fi, almacenamiento y soluciones de colaboración para organizaciones.", "Tecnología para redes y colaboración."),
 ("IDEMIA", "idemia", "acceso ciberseguridad", "Biometría e identidad: lectores faciales y de huella para control de acceso de alta seguridad.", "Biometría de alta seguridad."),
 ("Intellinet", "intellinet", "redes cableado", "Switches, cableado, patch cords y accesorios de conectividad para redes empresariales.", "Conectividad práctica para tu red."),
 ("Kaspersky", "kaspersky", "ciberseguridad computo", "Protección de endpoints, servidores y correo contra malware y ransomware, con administración centralizada.", "Protección para equipos y servidores."),
 ("Kingston", "kingston", "computo videovigilancia", "Memorias RAM, unidades SSD y almacenamiento flash para mejorar el rendimiento de equipos y servidores.", "Memorias y SSD para más rendimiento."),
 ("LAPP", "lapp", "cableado redes", "Cables y conectividad industrial para automatización, maquinaria y control.", "Cables industriales de alta calidad."),
 ("Lenovo", "lenovo", "computo", "Laptops, equipos de escritorio, estaciones de trabajo y servidores para empresas.", "Equipos de cómputo confiables para cada puesto de trabajo."),
 ("LinkedPRO", "linkedpro", "cableado redes energia", "Cableado, fibra óptica, racks y accesorios de conectividad para redes y videovigilancia.", "Cableado y conectividad para tus proyectos."),
 ("Microsoft", "microsoft", "computo ciberseguridad audio-video", "Licenciamiento de Windows, Microsoft 365, Teams y soluciones de productividad y seguridad en la nube.", "Software de productividad y colaboración."),
 ("MikroTik", "mikrotik", "redes", "Routers, switches y enlaces inalámbricos con gran flexibilidad de configuración.", "Routing y enlaces inalámbricos flexibles."),
 ("Motorola", "motorola", "redes videovigilancia", "Radios de comunicación bidireccional y soluciones de comunicación para equipos de trabajo.", "Radiocomunicación para equipos de trabajo."),
 ("Multilink", "multilink", "cableado redes", "Gabinetes, fibra óptica y accesorios para redes de telecomunicaciones en interior y exterior.", "Infraestructura para redes de telecomunicaciones."),
 ("Optronics", "optronics", "cableado redes", "Cables, conectores, distribuidores y accesorios de fibra óptica para redes y enlaces.", "Fibra óptica para tus enlaces."),
 ("Panduit", "panduit", "cableado redes", "Cableado estructurado de cobre y fibra, organización de racks e infraestructura física para centros de datos.", "Cableado estructurado de alto desempeño."),
 ("PLANET", "planet", "redes cableado videovigilancia", "Switches administrables, PoE e industriales, y equipos de red para empresas y videovigilancia.", "Switches y PoE para redes profesionales."),
 ("QNAP", "qnap", "computo videovigilancia redes", "Almacenamiento NAS para respaldos, archivos compartidos, virtualización y videovigilancia.", "Almacenamiento NAS para tu información."),
 ("Rittal", "rittal", "cableado energia computo", "Gabinetes, racks y sistemas de climatización para infraestructura de TI y aplicaciones industriales.", "Racks y gabinetes para proteger tus equipos."),
 ("Rosslare", "rosslare", "acceso videovigilancia", "Controladores, lectores y software de control de acceso para proyectos comerciales y corporativos.", "Control de acceso para empresas."),
 ("Ruijie", "ruijie", "redes ciberseguridad", "Switches, Wi-Fi y redes administradas en la nube para empresas, escuelas y hoteles.", "Redes empresariales administradas en la nube."),
 ("SanDisk", "sandisk", "computo videovigilancia", "Memorias, unidades flash y SSD para almacenamiento y transferencia de información.", "Almacenamiento flash confiable."),
 ("Seagate", "seagate", "computo videovigilancia", "Discos duros para videovigilancia (SkyHawk), NAS (IronWolf) y almacenamiento empresarial de alta capacidad.", "Discos de alta capacidad para grabación continua."),
 ("Seco-Larm", "secolarm", "videovigilancia acceso energia", "Cerraduras electromagnéticas, botones, sensores y accesorios para control de acceso y seguridad.", "Accesorios para control de acceso y seguridad."),
 ("Siemon", "siemon", "cableado redes", "Cableado estructurado de cobre y fibra, y soluciones para centros de datos.", "Cableado de alto desempeño."),
 ("Streamax", "streamax", "videovigilancia redes", "Videovigilancia móvil y telemática para flotillas: DVR móviles, cámaras y asistencia a la conducción.", "Video y seguridad para flotillas."),
 ("Suprema", "suprema", "acceso ciberseguridad", "Lectores biométricos de rostro y huella, y plataformas de control de acceso y asistencia.", "Biometría para control de acceso y asistencia."),
 ("Synology", "synology", "computo videovigilancia redes", "NAS para respaldos, archivos compartidos, colaboración y videovigilancia.", "Almacenamiento y respaldo para tu empresa."),
 ("Teltonika", "teltonika", "redes ciberseguridad", "Routers y gateways industriales 4G/5G para conectividad remota e IoT.", "Conectividad celular industrial."),
 ("Thorsman", "thorsman", "cableado energia", "Canaletas, ductos y accesorios para la canalización eléctrica y de datos.", "Canalización eléctrica y de datos."),
 ("Total Ground", "total-ground", "energia cableado", "Sistemas de tierra física, pararrayos y protección contra descargas para instalaciones eléctricas.", "Tierras físicas y protección contra descargas."),
 ("TP-Link", "tp-link", "redes videovigilancia", "Switches, puntos de acceso, routers y la línea Omada de administración en la nube.", "Conectividad confiable con excelente relación costo-beneficio."),
 ("Ubiquiti", "ubiquiti", "redes videovigilancia acceso", "Equipos de red empresarial con administración centralizada: Wi-Fi, switching, enlaces y videovigilancia UniFi.", "Redes empresariales administradas de forma centralizada."),
 ("UNV (Uniview)", "unv", "videovigilancia acceso", "Cámaras IP, grabadores y plataformas de videovigilancia para proyectos de todos los tamaños.", "Videovigilancia IP profesional."),
 ("Velcro", "velcro", "cableado", "Cinchos y amarres reutilizables para organizar y mantener ordenado el cableado.", "Organización práctica del cableado."),
 ("Viakon", "viakon", "cableado energia videovigilancia", "Cables eléctricos y de telecomunicaciones de Conductores Monterrey para instalaciones residenciales e industriales.", "Cables eléctricos hechos en México."),
 ("Western Digital", "western-digital", "computo videovigilancia", "Discos duros y almacenamiento para videovigilancia, NAS y centros de datos, incluidas las líneas WD Purple y WD Red.", "Almacenamiento especializado para videovigilancia y datos."),
 ("Yonusa", "yonusa", "videovigilancia acceso", "Energizadores y accesorios para cercas eléctricas perimetrales.", "Protección perimetral con cercas eléctricas."),
 ("Zebra", "zebra", "computo acceso", "Impresoras de etiquetas, lectores de códigos y computadoras móviles para logística, almacén y punto de venta.", "Identificación y movilidad para tu operación."),
 ("ZKTeco", "zkteco", "acceso videovigilancia", "Biométricos, control de acceso, asistencia, torniquetes y cerraduras inteligentes.", "Control de acceso y asistencia biométrica."),
 # --- Marcas adicionales (correo de Wiccom, 5-oct-2026)
 ("BenQ", "benq", "audio-video", "Proyectores, pantallas interactivas y monitores profesionales para aulas, salas de juntas y diseño.", "Proyección y pantallas interactivas para presentar y enseñar."),
 ("Extron", "extron", "audio-video", "Distribución, conmutación y control de señales de audio y video para salas, auditorios y espacios corporativos.", "Distribución y control audiovisual profesional."),
 ("Kramer", "kramer", "audio-video", "Soluciones de conmutación, distribución y colaboración audiovisual para salas de juntas y aulas.", "Integración audiovisual para espacios de colaboración."),
 ("LG", "lg", "audio-video", "Pantallas profesionales, señalización digital, videowalls y monitores para empresas.", "Pantallas profesionales y señalización digital."),
 ("Logitech", "logitech", "audio-video", "Cámaras, barras de video y kits de videoconferencia para salas de juntas y trabajo híbrido.", "Videoconferencia para salas de todos los tamaños."),
 ("Poly", "poly", "audio-video", "Sistemas de videoconferencia, audífonos y teléfonos para comunicación y colaboración empresarial.", "Audio y video claros para cada reunión."),
 ("Samsung", "samsung", "audio-video", "Pantallas profesionales, señalización digital, pizarrones interactivos y videowalls.", "Pantallas profesionales y videowalls."),
 ("Sony", "sony", "audio-video", "Pantallas profesionales, proyectores y cámaras para presentación de contenidos y producción audiovisual.", "Imagen profesional para tus espacios."),
 ("Yealink", "yealink", "audio-video", "Equipos de videoconferencia, teléfonos IP y dispositivos de colaboración certificados para Microsoft Teams y Zoom.", "Colaboración y videoconferencia empresarial."),
 ("TruVision", "truvision", "videovigilancia acceso", "Cámaras, grabadores y software de videovigilancia con integración a sistemas de control de acceso.", "Videovigilancia profesional integrada."),
 ("Lenel", "lenel", "videovigilancia acceso", "Plataformas de seguridad física (LenelS2) que integran control de acceso, videovigilancia y gestión de eventos.", "Seguridad física y control de acceso a nivel empresarial."),
]
BRANDS = [dict(name=n, slug=sl, cats=c, desc=d, lead=l, sols=[CAT_SOL[k] for k in c.split()]) for n, sl, c, d, l in _B]
BRAND = {b["slug"]: b for b in BRANDS}

# 16 marcas destacadas del carrusel de Inicio (orden definido por Wiccom).
MARQUEE = ["hikvision", "dahua", "ubiquiti", "cisco", "hpe-aruba", "fortinet", "panduit", "commscope",
           "apc", "eaton", "dell", "hp", "rittal", "zkteco", "western-digital", "seagate"]

# Líneas de producto y aplicaciones por categoría (para las páginas de marca).
# Para una marca en particular puedes agregar lines=[...] y apps=[...] en su dict.
LINES_BY_CAT = {
    "videovigilancia": [("cctv", "Cámaras IP y analógicas"), ("server", "Grabadores NVR / DVR"), ("bell", "Alarmas e intrusión")],
    "acceso": [("key", "Lectores y biometría"), ("card", "Credenciales e identidad"), ("lock", "Cerraduras y automatización")],
    "redes": [("network", "Switches y routers"), ("wifi", "Wi-Fi y enlaces inalámbricos"), ("phone", "Telefonía IP")],
    "cableado": [("link", "Cableado de cobre"), ("activity", "Fibra óptica"), ("rack", "Racks, gabinetes y canalización")],
    "energia": [("battery", "UPS y baterías"), ("zap", "Regulación y protección"), ("rack", "Distribución de energía")],
    "ciberseguridad": [("shield", "Firewalls"), ("monitor", "Protección de endpoints"), ("lock", "Acceso seguro")],
    "computo": [("monitor", "Equipos de cómputo"), ("server", "Servidores y almacenamiento"), ("printer", "Impresión y periféricos")],
    "audio-video": [("video", "Videoconferencia"), ("monitor", "Pantallas y proyección"), ("sound", "Audio y accesorios")],
}
APPS_BY_CAT = {
    "videovigilancia": ["Oficinas y corporativos", "Comercios y plazas", "Industria y almacenes", "Escuelas"],
    "acceso": ["Accesos de personal", "Fraccionamientos", "Estacionamientos", "Industria"],
    "redes": ["Oficinas", "Naves industriales", "Campus y escuelas", "Hoteles y hospitales"],
    "cableado": ["Centros de datos", "Edificios corporativos", "Naves industriales", "Sites de telecomunicaciones"],
    "energia": ["Sites y centros de datos", "Videovigilancia", "Oficinas", "Industria"],
    "ciberseguridad": ["Oficinas", "Sucursales", "Trabajo remoto", "Centros de datos"],
    "computo": ["Puestos de trabajo", "Áreas de diseño e ingeniería", "Centros de datos", "Punto de venta"],
    "audio-video": ["Salas de juntas", "Capacitación", "Recepciones", "Auditorios"],
}

# Contenido de cada solución (documentos de Wiccom, oct-2026).
# Orden de la página: banner · introducción · ¿Qué incluye? · beneficios · aplicaciones (fotos)
#                     · Enfoque Wiccom · marcas · otras soluciones · CTA final
# Fotos de aplicaciones: assets/img/soluciones/apps/<slug>-<n>.webp (n = orden de la lista "apps")
INC_SUB = "Tecnologías y componentes que integramos de acuerdo con las necesidades de cada proyecto."
OTHERS_SUB = "Integramos distintas tecnologías dentro de una misma solución, de acuerdo con las necesidades de cada proyecto."

SOLUTIONS = [
 dict(slug="videovigilancia", name="Videovigilancia y Seguridad Electrónica", icon="cctv",
   short="Soluciones de videovigilancia, monitoreo, grabación, alarmas y seguridad electrónica para proteger instalaciones, personas y activos.",
   card="Seguridad que te da tranquilidad",
   h1=("Videovigilancia para proteger", "lo que más importa"), eyebrow="Videovigilancia · Alarmas · Monitoreo · Seguridad electrónica",
   lead="Soluciones con cámaras IP, grabadores, monitoreo, analíticos y alarmas, diseñadas para empresas y proyectos de cualquier tamaño.",
   script=("Seguridad que", "te da tranquilidad"),
   feats=[("shield", "Protege tu patrimonio"), ("users", "Mayor control operativo"), ("chart", "Previene incidentes"), ("gear", "Tecnología escalable")],
   intro="En Wiccom integramos soluciones de videovigilancia y seguridad electrónica diseñadas para proteger personas, instalaciones y activos mediante tecnologías confiables y escalables.",
   inc_sub=INC_SUB,
   includes=[("video", "Cámaras de videovigilancia", "Cámaras IP y analógicas para interior y exterior, con opciones de alta resolución, visión nocturna, analítica y WDR."),
             ("db", "Grabación y almacenamiento", "NVR, DVR y soluciones de almacenamiento para conservar y administrar las grabaciones de forma segura."),
             ("monitor", "Monitoreo y gestión remota", "Supervisa cámaras y eventos en tiempo real desde computadora, tablet o dispositivo móvil."),
             ("bell", "Alarmas e intrusión", "Paneles, sensores, sirenas y dispositivos de detección para identificar y notificar eventos de seguridad.")],
   ben_sub="Mayor visibilidad, control y respaldo para tu operación.",
   benefits=[("shield", "Más seguridad", "Ayuda a proteger a las personas, instalaciones y activos mediante monitoreo y detección de eventos."),
             ("clock", "Supervisión en tiempo real", "Mantén visibilidad de tus espacios y eventos desde ubicaciones remotas."),
             ("file", "Evidencia y control", "Conserva grabaciones y registros para seguimiento, investigación y cumplimiento."),
             ("chart", "Escalabilidad", "Amplía la solución conforme crecen tus instalaciones, sucursales o necesidades operativas.")],
   apps_intro="Nuestras soluciones de videovigilancia y seguridad electrónica se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Oficinas y corporativos", "Monitoreo de accesos, áreas comunes y zonas de trabajo."),
         ("Comercios y tiendas", "Supervisión de puntos de venta, áreas de atención y zonas sensibles."),
         ("Centros de distribución", "Monitoreo de almacenes, patios, accesos y operaciones logísticas."),
         ("Industria y manufactura", "Vigilancia de áreas productivas, perímetros y zonas críticas."),
         ("Residenciales y edificios", "Supervisión de accesos, áreas comunes y perímetros.")],
   focus=("Una solución diseñada para cada proyecto",
          "Cada proyecto de videovigilancia requiere considerar factores como áreas de cobertura, condiciones de iluminación, resolución, almacenamiento, infraestructura de red, tiempo de retención de grabaciones y necesidades de monitoreo.",
          "En Wiccom analizamos estos elementos para definir una solución adecuada a las condiciones de cada instalación, procurando compatibilidad entre tecnologías, facilidad de operación y capacidad de crecimiento."),
   brands_sub="Integramos soluciones con fabricantes especializados en videovigilancia y seguridad electrónica, seleccionando la tecnología adecuada para cada proyecto.",
   brands=["hikvision", "dahua", "hanwha", "unv", "truvision", "lenel", "epcom", "ubiquiti", "streamax", "dsc", "honeywell", "secolarm", "yonusa", "western-digital", "seagate", "qnap", "synology"],
   cta=("¿Listo para un entorno más seguro?", "Te ayudamos a diseñar la solución de videovigilancia ideal para tu empresa o proyecto."),
   kw="videovigilancia Monterrey, cámaras de seguridad empresas, CCTV, cámaras IP, NVR, alarmas"),
 dict(slug="control-de-acceso", name="Control de Acceso e Identidad", icon="lock",
   short="Soluciones de control de acceso, biometría e identificación para administrar de forma segura el ingreso a instalaciones y áreas restringidas.",
   card="Personas, espacios y mayor seguridad",
   h1=("Control de acceso para", "espacios más seguros"), eyebrow="Biometría · Identificación · Credenciales · Barreras",
   lead="Controla quién entra, cuándo y por dónde con lectores biométricos, credenciales, torniquetes y barreras vehiculares.",
   script=("Acceso seguro,", "operación fluida"),
   feats=[("key", "Accesos controlados"), ("users", "Registro de personal"), ("shield", "Áreas restringidas"), ("card", "Credenciales y biometría")],
   intro="En Wiccom integramos soluciones de control de acceso e identidad para administrar de forma segura el ingreso de personas a áreas, instalaciones y recursos restringidos.",
   inc_sub=INC_SUB,
   includes=[("key", "Lectores y biometría", "Identificación mediante huella, rostro, tarjeta o código para controlar el ingreso a puertas y áreas restringidas."),
             ("card", "Credenciales e identidad", "Tarjetas de proximidad, credenciales móviles y diferentes tecnologías de identificación para usuarios y visitantes."),
             ("truck", "Accesos vehiculares", "Barreras, identificación vehicular, lectura de placas y automatización de accesos y portones."),
             ("monitor", "Software y gestión", "Administración de usuarios, permisos, horarios, niveles de acceso, eventos y reportes.")],
   ben_sub="Mayor control, seguridad y trazabilidad para tu operación.",
   benefits=[("shield", "Mayor seguridad", "Solo las personas autorizadas acceden a cada área."),
             ("clock", "Control y registro", "Mantén registros confiables de entradas y salidas."),
             ("file", "Trazabilidad", "Consulta el historial de eventos para seguimiento, auditorías e investigaciones."),
             ("gear", "Integración", "Integra el control de acceso con videovigilancia, alarmas y otros sistemas de seguridad.")],
   apps_intro="Nuestras soluciones de control de acceso e identidad se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Corporativos", "Control de acceso para oficinas, edificios empresariales y áreas restringidas."),
         ("Plantas industriales", "Gestión de accesos para personal, contratistas y zonas operativas."),
         ("Centros de distribución", "Control de ingreso en almacenes, patios, áreas logísticas y zonas de carga."),
         ("Estacionamientos", "Automatización de accesos vehiculares mediante barreras, lectores e identificación."),
         ("Instituciones educativas", "Control de acceso para alumnos, personal, visitantes y áreas de uso restringido.")],
   focus=("Una solución diseñada para cada proyecto",
          "El sistema adecuado depende del número de usuarios, cantidad de accesos, nivel de seguridad requerido, tecnología de identificación, infraestructura existente y necesidad de integración con otros sistemas.",
          "En Wiccom analizamos estos factores para definir una solución que responda a las necesidades actuales del proyecto y permita futuras ampliaciones."),
   brands_sub="Integramos soluciones con fabricantes especializados en control de acceso, identidad y automatización.",
   brands=["hid", "suprema", "zkteco", "idemia", "rosslare", "accesspro", "came", "faac", "hikvision", "dahua", "honeywell", "secolarm", "ubiquiti"],
   cta=("¿Quieres tener mayor control sobre tus accesos?", "Diseñamos e integramos la solución de control de acceso adecuada para tu operación."),
   kw="control de acceso Monterrey, biométricos, identificación, torniquetes, barreras vehiculares"),
 dict(slug="redes-y-telecomunicaciones", name="Redes y Telecomunicaciones", icon="network",
   short="Soluciones de redes, Wi-Fi, switching, routing, telefonía IP y telecomunicaciones para mantener una conectividad confiable y escalable.",
   card="Conectividad confiable y escalable",
   h1=("Redes y telecomunicaciones para una", "operación siempre conectada"), eyebrow="Wi-Fi · Switching · Routing · Telefonía IP",
   lead="Diseñamos e implementamos redes LAN/WLAN, enlaces inalámbricos y telefonía IP con equipos de nivel empresarial.",
   script=("Conectividad", "sin límites"),
   feats=[("wifi", "Wi-Fi empresarial"), ("network", "Red administrable"), ("phone", "Telefonía IP"), ("trend", "Lista para crecer")],
   intro="Diseñamos e integramos redes empresariales estables, seguras y escalables para conectar usuarios, dispositivos, aplicaciones y distintas ubicaciones.",
   inc_sub=INC_SUB,
   includes=[("wifi", "Redes inalámbricas", "Diseño, site survey, puntos de acceso empresariales y roaming para una cobertura Wi-Fi estable y eficiente."),
             ("network", "Switching y routing", "Switches administrables, PoE, VLAN, routing y segmentación para optimizar el tráfico de la red."),
             ("activity", "Enlaces inalámbricos", "Conectividad punto a punto y punto-multipunto para enlazar edificios, instalaciones o ubicaciones remotas."),
             ("phone", "Telefonía IP y comunicaciones", "Soluciones de telefonía IP, conmutadores y dispositivos de comunicación para entornos empresariales.")],
   ben_sub="Conectividad confiable, mayor control y capacidad de crecimiento para tu operación.",
   benefits=[("zap", "Mayor rendimiento", "Optimiza el acceso a aplicaciones, servicios en la nube y recursos de red."),
             ("refresh", "Mayor disponibilidad", "Una red correctamente diseñada facilita la operación, el mantenimiento y la detección de fallas."),
             ("shield", "Mayor seguridad", "Segmenta usuarios, dispositivos y tráfico para mejorar el control y protección de la infraestructura."),
             ("trend", "Escalabilidad", "Prepara la red para incorporar nuevos usuarios, dispositivos, servicios y ubicaciones.")],
   apps_intro="Nuestras soluciones de redes y telecomunicaciones se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Oficinas y corporativos", "Redes empresariales para usuarios, dispositivos, salas de juntas y servicios en la nube."),
         ("Industria y manufactura", "Conectividad para áreas administrativas, operativas y procesos que requieren disponibilidad de red."),
         ("Campus e instituciones educativas", "Cobertura Wi-Fi y conectividad para aulas, áreas comunes, oficinas y servicios digitales."),
         ("Hoteles y hospitales", "Redes de alta disponibilidad para usuarios, servicios, dispositivos y aplicaciones críticas."),
         ("Sucursales y múltiples ubicaciones", "Interconexión segura entre oficinas, sucursales y sitios remotos.")],
   focus=("Una red diseñada para las necesidades de cada proyecto",
          "El diseño de una red depende de factores como número de usuarios y dispositivos, cobertura requerida, aplicaciones utilizadas, ancho de banda, seguridad, disponibilidad e infraestructura existente.",
          "En Wiccom analizamos estos elementos para definir una arquitectura de red que responda a las necesidades actuales del proyecto y permita futuras ampliaciones."),
   brands_sub="Integramos soluciones con fabricantes especializados en redes y telecomunicaciones, seleccionando la tecnología adecuada para cada proyecto.",
   brands=["cisco", "hpe-aruba", "huawei", "ubiquiti", "cambium-networks", "mikrotik", "ruijie", "tp-link", "planet", "grandstream", "fortinet"],
   cta=("¿Necesitas mejorar o ampliar tu red?", "Analizamos tu infraestructura y diseñamos una solución de conectividad adecuada para tu operación."),
   kw="redes empresariales Monterrey, wifi empresarial, switches, telefonía IP, enlaces inalámbricos"),
 dict(slug="cableado-fibra-e-infraestructura", name="Cableado, Fibra e Infraestructura", icon="rack",
   short="Soluciones de cableado estructurado, fibra óptica, racks, gabinetes y canalización para construir una infraestructura confiable y preparada para crecer.",
   card="Infraestructura lista para crecer",
   h1=("Cableado e infraestructura", "que soporta tu operación"), eyebrow="Cableado estructurado · Fibra óptica · Racks · Canalización",
   lead="Cableado de cobre y fibra óptica, racks, gabinetes y canalización instalados con orden, certificación y documentación.",
   script=("Infraestructura", "que perdura"),
   feats=[("link", "Cableado certificado"), ("activity", "Fibra óptica"), ("rack", "Racks y gabinetes"), ("layers", "Canalización ordenada")],
   intro="Diseñamos e integramos la infraestructura física que soporta tu red, con cableado, fibra óptica, racks y canalización preparados para operar de forma ordenada, confiable y escalable.",
   inc_sub=INC_SUB,
   includes=[("link", "Cableado estructurado", "Soluciones en categorías 6 y 6A, certificación de nodos, etiquetado y documentación de la instalación."),
             ("activity", "Fibra óptica", "Backbones, enlaces entre edificios, empalmes por fusión y pruebas de desempeño de los enlaces."),
             ("rack", "Racks y gabinetes", "Racks, gabinetes y organización de equipos y cableado para cuartos técnicos y sites."),
             ("layers", "Canalización e infraestructura", "Charola, tubería, canaleta y sistemas de soporte para una instalación ordenada y segura.")],
   ben_sub="Infraestructura ordenada, documentada y preparada para soportar el crecimiento de tu operación.",
   benefits=[("refresh", "Mayor confiabilidad", "Una instalación correctamente diseñada y certificada ayuda a reducir fallas, pérdidas de señal y problemas de conectividad."),
             ("file", "Orden y documentación", "Etiquetado, identificación y documentación facilitan mantenimientos, cambios y futuras ampliaciones."),
             ("trend", "Preparada para crecer", "Una infraestructura bien planeada permite incorporar nuevos nodos, equipos y tecnologías."),
             ("check", "Desempeño verificable", "Las pruebas y certificaciones permiten comprobar el desempeño de los enlaces instalados.")],
   apps_intro="Nuestras soluciones de cableado, fibra e infraestructura se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Oficinas y corporativos", "Infraestructura de cableado para estaciones de trabajo, salas, telefonía y dispositivos de red."),
         ("Centros de datos y sites", "Organización de racks, fibra, cobre y enlaces para infraestructura tecnológica crítica."),
         ("Industria y manufactura", "Cableado e infraestructura para áreas administrativas, operativas y entornos industriales."),
         ("Hospitales e instituciones educativas", "Infraestructura para redes de datos, comunicaciones y diferentes servicios tecnológicos."),
         ("Edificios y proyectos nuevos", "Planeación e instalación de infraestructura desde las etapas iniciales del proyecto.")],
   focus=("Infraestructura diseñada para cada proyecto",
          "El diseño de una infraestructura de cableado depende de factores como cantidad y ubicación de nodos, distancias, capacidad requerida, tipo de red, condiciones del sitio y posibilidades de crecimiento.",
          "En Wiccom analizamos estos elementos para definir una solución ordenada, documentada y adecuada a las necesidades actuales del proyecto, considerando también futuras ampliaciones."),
   brands_sub="Integramos soluciones con fabricantes especializados en cableado, fibra e infraestructura, seleccionando los componentes adecuados para cada proyecto.",
   brands=["commscope", "panduit", "siemon", "belden", "viakon", "condumex", "lapp", "charofil", "thorsman", "rittal", "hoffman", "multilink", "fiberhome", "fluke"],
   cta=("¿Necesitas renovar o ampliar tu infraestructura?", "Diseñamos e integramos la infraestructura de cableado y fibra adecuada para las necesidades de tu proyecto."),
   kw="cableado estructurado Monterrey, fibra óptica, racks, gabinetes, canalización, certificación"),
 dict(slug="energia-y-respaldo", name="Energía y Respaldo", icon="zap",
   short="Soluciones de UPS, baterías, protección eléctrica y respaldo de energía para mantener operativa y protegida la infraestructura tecnológica.",
   card="Tu operación siempre en marcha",
   h1=("Energía y respaldo para que", "tu operación no se detenga"), eyebrow="UPS · Baterías · Protección eléctrica",
   lead="UPS, baterías, reguladores, PDU y protección eléctrica dimensionados para tus equipos críticos.",
   script=("Energía que", "no se detiene"),
   feats=[("battery", "Respaldo continuo"), ("shield", "Equipos protegidos"), ("activity", "Energía estable"), ("refresh", "Continuidad")],
   intro="Diseñamos soluciones de protección y respaldo de energía para mantener operativa tu infraestructura tecnológica ante variaciones, fallas y cortes eléctricos.",
   inc_sub=INC_SUB,
   includes=[("battery", "UPS y baterías", "Equipos interactivos y en línea de doble conversión, con bancos de baterías y autonomía de acuerdo con la carga y tiempo de respaldo requerido."),
             ("activity", "Regulación y protección", "Reguladores, supresores de picos, protección contra sobretensiones y soluciones de puesta a tierra."),
             ("rack", "Distribución de energía", "PDU básicas, medidas y administrables para racks, sites y centros de datos."),
             ("monitor", "Monitoreo y gestión", "Tarjetas de red y software para supervisión, alertas, registro de eventos y apagado seguro de equipos.")],
   ben_sub="Mayor continuidad, protección y control para tu infraestructura tecnológica.",
   benefits=[("refresh", "Continuidad operativa", "Mantén funcionando los sistemas críticos durante interrupciones y variaciones de energía."),
             ("shield", "Protección de equipos", "Ayuda a proteger la infraestructura ante picos, sobretensiones, caídas de voltaje y cortes eléctricos."),
             ("chart", "Menor impacto operativo", "Reduce interrupciones, pérdida de información y tiempos muertos asociados a problemas de energía."),
             ("bell", "Monitoreo oportuno", "Recibe alertas sobre estado de baterías, carga, autonomía y eventos eléctricos.")],
   apps_intro="Nuestras soluciones de energía y respaldo se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Centros de datos y sites", "Respaldo para servidores, almacenamiento, switches y equipos de infraestructura crítica."),
         ("Oficinas y corporativos", "Protección para estaciones de trabajo, equipos de red y servicios esenciales."),
         ("Videovigilancia y seguridad electrónica", "Respaldo para cámaras, grabadores, controles de acceso y sistemas de seguridad."),
         ("Comercios y puntos de venta", "Protección para terminales, comunicaciones, equipos de cobro y sistemas operativos."),
         ("Industria y manufactura", "Respaldo y protección para infraestructura tecnológica y equipos críticos de operación.")],
   focus=("El respaldo adecuado para cada operación",
          "La selección de un sistema de respaldo depende de factores como carga conectada, potencia requerida, autonomía, criticidad de los equipos, condiciones eléctricas y posibilidades de crecimiento.",
          "En Wiccom analizamos estos elementos para definir una solución adecuada, evitando tanto el subdimensionamiento como el sobredimensionamiento y considerando futuras ampliaciones."),
   brands_sub="Integramos soluciones con fabricantes especializados en energía, respaldo y protección eléctrica, seleccionando la tecnología adecuada para cada proyecto.",
   brands=["apc", "eaton", "cdp", "cyberpower", "total-ground"],
   cta=("¿Qué pasaría si se va la luz hoy?", "Calculamos la carga y autonomía necesarias para definir el respaldo adecuado para tu operación."),
   kw="UPS Monterrey, no break empresarial, respaldo de energía, baterías, reguladores"),
 dict(slug="ciberseguridad", name="Ciberseguridad", icon="shield",
   short="Soluciones de seguridad de red, firewalls, protección de endpoints y acceso seguro para fortalecer la infraestructura tecnológica de la organización.",
   card="Protección para tu información",
   h1=("Ciberseguridad para proteger", "tu información y tu operación"), eyebrow="Firewalls · Endpoints · Acceso seguro · Monitoreo",
   lead="Firewalls de nueva generación, protección de equipos, acceso remoto seguro y políticas para reducir riesgos en tu red.",
   script=("Tu información,", "siempre protegida"),
   feats=[("shield", "Red protegida"), ("lock", "Acceso seguro"), ("monitor", "Equipos protegidos"), ("eye", "Visibilidad")],
   intro="Diseñamos e integramos soluciones de ciberseguridad para proteger usuarios, dispositivos, redes y accesos, de acuerdo con las necesidades y nivel de riesgo de cada organización.",
   inc_sub="Tecnologías y controles que integramos de acuerdo con las necesidades de cada proyecto.",
   includes=[("shield", "Firewalls y seguridad perimetral", "Firewalls de nueva generación con filtrado web, control de aplicaciones, prevención de intrusiones y segmentación de red."),
             ("monitor", "Protección de endpoints", "Antivirus, EDR y herramientas de protección para computadoras y servidores, con administración centralizada."),
             ("lock", "Acceso remoto seguro", "VPN, autenticación y controles de acceso para conectar de forma segura usuarios, sucursales y personal remoto."),
             ("eye", "Monitoreo y políticas de seguridad", "Supervisión de eventos, reportes, políticas de uso y controles para detectar y reducir riesgos.")],
   ben_sub="Mayor protección, visibilidad y control para tu infraestructura tecnológica.",
   benefits=[("shield", "Reducción de riesgos", "Ayuda a reducir la exposición a malware, ransomware, accesos no autorizados y otras amenazas."),
             ("refresh", "Continuidad operativa", "Una estrategia de seguridad adecuada ayuda a disminuir el impacto de incidentes sobre la operación."),
             ("eye", "Mayor visibilidad", "Obtén mayor control sobre usuarios, dispositivos, accesos y eventos dentro de la red."),
             ("file", "Apoyo al cumplimiento", "Facilita la aplicación de políticas, controles y registros relacionados con protección de información y auditorías.")],
   apps_intro="Nuestras soluciones de ciberseguridad se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Oficinas y corporativos", "Protección de usuarios, dispositivos, aplicaciones y acceso a recursos empresariales."),
         ("Sucursales y múltiples ubicaciones", "Seguridad y conectividad controlada entre oficinas, sucursales y sitios remotos."),
         ("Trabajo remoto", "Acceso seguro para colaboradores que se conectan desde fuera de las instalaciones."),
         ("Centros de datos y servicios críticos", "Protección de servidores, aplicaciones, servicios y recursos de infraestructura."),
         ("Salud e instituciones educativas", "Protección de información, usuarios y servicios en entornos con múltiples perfiles de acceso.")],
   focus=("Protección adecuada para cada entorno",
          "La estrategia de ciberseguridad depende de factores como cantidad de usuarios y dispositivos, infraestructura existente, accesos remotos, aplicaciones utilizadas, información que se maneja y nivel de exposición a riesgos.",
          "En Wiccom analizamos estos elementos para definir una solución adecuada, combinando distintas capas de protección y considerando las necesidades actuales y futuras de la organización."),
   brands_sub="Integramos soluciones con fabricantes especializados en ciberseguridad, seleccionando las tecnologías adecuadas para cada entorno y nivel de protección requerido.",
   brands=["fortinet", "kaspersky", "check-point", "microsoft"],
   cta=("¿Qué tan protegida está tu red?", "Analizamos tu infraestructura para definir una estrategia de seguridad adecuada a tus necesidades y nivel de riesgo."),
   kw="ciberseguridad Monterrey, firewall empresarial, Fortinet, antivirus empresarial, VPN"),
 dict(slug="computo-y-ti", name="Cómputo y TI", icon="monitor",
   short="Soluciones de cómputo, servidores, almacenamiento, impresión y equipamiento TI para impulsar la productividad y operación de las organizaciones.",
   card="Tecnología para trabajar mejor",
   h1=("Cómputo y TI para", "equipos más productivos"), eyebrow="Equipos · Servidores · Almacenamiento · Impresión",
   lead="Computadoras, estaciones de trabajo, servidores, almacenamiento, impresión y licenciamiento para cada área de tu empresa.",
   script=("Tecnología para", "trabajar mejor"),
   feats=[("monitor", "Equipos por perfil"), ("server", "Servidores"), ("hdd", "Almacenamiento"), ("award", "Garantía de fábrica")],
   intro="Integramos soluciones de cómputo, servidores, almacenamiento, impresión y equipamiento TI de acuerdo con las necesidades de cada usuario, área y operación.",
   inc_sub="Tecnologías y equipos que integramos de acuerdo con las necesidades de cada proyecto.",
   includes=[("monitor", "Computadoras y laptops", "Equipos de escritorio, laptops y estaciones de trabajo empresariales para distintos perfiles de usuario."),
             ("server", "Servidores e infraestructura", "Servidores para aplicaciones, virtualización, bases de datos y servicios empresariales."),
             ("hdd", "Almacenamiento", "NAS, discos duros, SSD y soluciones de almacenamiento para administrar y proteger la información."),
             ("printer", "Impresión y periféricos", "Impresoras, etiquetadoras, lectores, monitores, accesorios y dispositivos para complementar la operación.")],
   ben_sub="Equipamiento confiable, estandarizado y preparado para las necesidades de tu operación.",
   benefits=[("trend", "Mayor productividad", "Equipos adecuados para las tareas, aplicaciones y necesidades de cada usuario."),
             ("layers", "Estandarización", "Una plataforma homogénea facilita la administración, soporte y mantenimiento de la infraestructura."),
             ("award", "Mayor confiabilidad", "Seleccionamos equipos y componentes de acuerdo con las necesidades de desempeño y continuidad de la operación."),
             ("chart", "Escalabilidad", "Permite incorporar nuevos usuarios, equipos, almacenamiento y capacidad conforme crece la organización.")],
   apps_intro="Nuestras soluciones de cómputo y TI se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Oficinas y corporativos", "Equipos de cómputo para usuarios administrativos, comerciales y operativos."),
         ("Diseño e ingeniería", "Estaciones de trabajo para aplicaciones profesionales que requieren mayor capacidad de procesamiento y gráficos."),
         ("Centros de datos y sites", "Servidores, almacenamiento y equipamiento para servicios e infraestructura empresarial."),
         ("Almacenes y logística", "Equipos, terminales, impresión y dispositivos para apoyar procesos operativos y de distribución."),
         ("Instituciones educativas", "Equipamiento para aulas, laboratorios, áreas administrativas y servicios tecnológicos.")],
   focus=("Equipamiento adecuado para cada perfil y operación",
          "La selección de equipos de cómputo y TI depende de factores como las aplicaciones utilizadas, nivel de desempeño requerido, movilidad, almacenamiento, compatibilidad, seguridad y posibilidades de crecimiento.",
          "En Wiccom analizamos estos elementos para definir una solución adecuada para cada perfil de usuario y área de operación, buscando estandarización, facilidad de administración y capacidad de crecimiento."),
   brands_sub="Integramos soluciones con fabricantes especializados en cómputo, servidores, almacenamiento y equipamiento TI, seleccionando la tecnología adecuada para cada proyecto.",
   brands=["dell", "hp", "hpe", "lenovo", "asus", "apple", "microsoft", "western-digital", "seagate", "kingston", "synology", "qnap", "zebra", "epson"],
   cta=("¿Vas a renovar o ampliar tu infraestructura de TI?", "Te ayudamos a definir el equipamiento adecuado de acuerdo con los perfiles de usuario, aplicaciones y presupuesto del proyecto."),
   kw="equipo de cómputo empresas Monterrey, laptops empresariales, servidores, NAS, impresión"),
 dict(slug="audio-video-y-colaboracion", name="Audio, Video y Colaboración", icon="video",
   short="Soluciones de videoconferencia, pantallas interactivas, proyección, distribución de audio y video y herramientas de colaboración para mejorar la comunicación y presentación de contenidos.",
   card="Comunicación sin distancias",
   h1=("Audio, video y colaboración para", "comunicarte mejor"), eyebrow="Videoconferencia · Pantallas · Proyección · Audio",
   lead="Salas de juntas, videoconferencia, pantallas interactivas, proyección y distribución de audio y video para tu empresa.",
   script=("Reuniones que", "sí conectan"),
   feats=[("video", "Videoconferencia"), ("monitor", "Pantallas interactivas"), ("sound", "Audio claro"), ("users", "Colaboración")],
   intro="Diseñamos e integramos soluciones de audio, video y colaboración para salas de juntas, capacitación, presentación de contenidos y comunicación híbrida.",
   inc_sub=INC_SUB,
   includes=[("video", "Videoconferencia", "Cámaras, barras de video, micrófonos y sistemas de colaboración para salas pequeñas, medianas y grandes."),
             ("monitor", "Pantallas e interactivos", "Pantallas profesionales, pantallas interactivas y soluciones de señalización digital para comunicación y presentación de contenidos."),
             ("play", "Proyección", "Proyectores y pantallas para auditorios, aulas, salas de capacitación y espacios de presentación."),
             ("sound", "Audio y distribución", "Soluciones de audio, voceo y distribución de señales de audio y video entre diferentes espacios.")],
   ben_sub="Mejor comunicación, colaboración y experiencia audiovisual para tus espacios.",
   benefits=[("users", "Mejor colaboración", "Facilita reuniones y comunicación entre oficinas, sucursales y personal remoto."),
             ("gear", "Mayor facilidad de uso", "Diseñamos espacios intuitivos y sencillos de operar para reducir tiempos de preparación."),
             ("eye", "Mejor experiencia audiovisual", "Audio e imagen adecuados para reuniones, presentaciones, capacitaciones y diferentes tipos de audiencia."),
             ("layers", "Estandarización de espacios", "Mantén una experiencia consistente entre salas, oficinas y ubicaciones.")],
   apps_intro="Nuestras soluciones de audio, video y colaboración se adaptan a distintos entornos y necesidades operativas.",
   apps=[("Salas de juntas", "Videoconferencia, audio y presentación de contenidos para reuniones presenciales e híbridas."),
         ("Aulas y capacitación", "Pantallas interactivas, proyección, audio y herramientas de colaboración para enseñanza y formación."),
         ("Auditorios", "Sistemas de proyección, audio y distribución de contenido para presentaciones y eventos."),
         ("Recepciones y espacios corporativos", "Pantallas profesionales y señalización digital para comunicación institucional e información."),
         ("Centros de monitoreo y control", "Videowalls, pantallas y distribución de señales para visualizar información y diferentes fuentes de video.")],
   focus=("Una solución diseñada para cada espacio",
          "El diseño de una solución audiovisual depende del tamaño del espacio, cantidad de usuarios, acústica, distancia de visualización, tipo de contenido, plataformas utilizadas y nivel de interacción requerido.",
          "En Wiccom analizamos estos elementos para definir una solución fácil de operar, adecuada a cada espacio y preparada para integrarse con la infraestructura tecnológica existente."),
   brands_sub="Integramos soluciones con fabricantes especializados en audio, video y colaboración, seleccionando la tecnología adecuada para cada espacio y necesidad de comunicación.",
   brands=["logitech", "epson", "benq", "huawei", "microsoft", "poly", "yealink", "samsung", "lg", "sony", "kramer", "extron"],
   cta=("¿Necesitas una mejor solución de audio y video?", "Diseñamos e integramos la solución adecuada para tus reuniones, presentaciones, capacitaciones y espacios de colaboración."),
   kw="videoconferencia Monterrey, salas de juntas, pantallas interactivas, proyectores, audio profesional"),
]
SOL = {s["slug"]: s for s in SOLUTIONS}

SERVICES = [
 dict(slug="asesoria-especializada", name="Asesoría especializada", icon="user", img="asesoria",
   short="Te orientamos para encontrar la solución adecuada según tus necesidades y presupuesto.",
   h1=("Asesoría especializada", "para encontrar la solución ideal"), eyebrow="Asesoría · Planeación · Tecnología",
   lead="Entendemos las necesidades de tu negocio y te orientamos con la mejor tecnología para que tomes decisiones seguras y alineadas a tus objetivos.",
   sub="Un servicio experto para convertir tus necesidades en soluciones tecnológicas de alto valor.",
   intro="Te acompañamos desde la idea hasta la implementación, analizando tus necesidades, recomendando la tecnología y diseñando una solución a la medida.",
   feats=[("shield", "Proyectos más seguros"), ("users", "Expertos a tu lado"), ("chart", "Tecnología que impulsa"), ("gear", "Resultados reales")],
   includes=[("file-search", "Análisis de necesidades", "Conocemos tu operación, objetivos y desafíos para entender lo que realmente necesitas."),
             ("gear", "Recomendación tecnológica", "Te sugerimos opciones de tecnología, marcas y arquitecturas según tus requerimientos."),
             ("scale", "Evaluación de alternativas", "Comparamos soluciones en costo, funcionalidad y escalabilidad."),
             ("map", "Planeación de solución", "Definimos el plan de implementación, recursos y próximos pasos.")],
   benefits=[("target", "Decisiones fundamentadas", "Con información técnica y análisis experto."),
             ("puzzle", "Solución a la medida", "Tecnología alineada a tus objetivos."),
             ("clock", "Ahorro de tiempo", "Evita pruebas y errores con la guía de especialistas."),
             ("chart", "Mejor inversión", "Maximiza el rendimiento de tu presupuesto.")],
   kw="asesoría tecnológica, consultoría TI Monterrey, diseño de proyectos de seguridad"),
 dict(slug="instalacion", name="Instalación", icon="wrench", img="instalacion",
   short="Implementación física de equipos, cableado e infraestructura tecnológica.",
   h1=("Instalación profesional", "con altos estándares"), eyebrow="Obra · Montaje · Cableado",
   lead="Montamos cámaras, cableado, racks y equipos con técnicos capacitados, cuidando la seguridad, el orden y los tiempos de tu proyecto.",
   sub="Implementación física cuidada, documentada y entregada funcionando.",
   intro="Planeamos la obra contigo, respetamos tus horarios de operación y te entregamos memoria técnica de todo lo instalado.",
   feats=[("shield", "Trabajo seguro"), ("users", "Técnicos certificados"), ("clock", "Tiempos cumplidos"), ("file", "Memoria técnica")],
   includes=[("map", "Levantamiento en sitio", "Visitamos tus instalaciones para definir rutas, alturas y materiales."),
             ("wrench", "Montaje de equipos", "Cámaras, lectores, puntos de acceso, pantallas y racks."),
             ("network", "Canalización y cableado", "Tubería, charola, cableado de cobre y fibra con buenas prácticas."),
             ("file", "Pruebas y entrega", "Certificación, etiquetado y memoria técnica del proyecto.")],
   benefits=[("award", "Calidad de obra", "Instalaciones limpias, ordenadas y duraderas."),
             ("shield", "Seguridad en sitio", "Personal con equipo de protección y protocolos."),
             ("clock", "Menos interrupciones", "Trabajamos en horarios que no afecten tu operación."),
             ("file", "Todo documentado", "Planos y registros para futuros mantenimientos.")],
   kw="instalación de cámaras Monterrey, instalación de cableado estructurado, montaje de racks"),
 dict(slug="configuracion-y-puesta-en-marcha", name="Configuración y puesta en marcha", icon="gear", img="configuracion",
   short="Dejamos tus equipos listos para operar de forma correcta y eficiente.",
   h1=("Configuración y puesta en marcha", "lista para operar"), eyebrow="Configuración · Pruebas · Arranque",
   lead="Configuramos redes, grabadores, firewalls, controles de acceso y servidores con las mejores prácticas de cada fabricante.",
   sub="Tus equipos funcionando desde el primer día, con la configuración correcta.",
   intro="Un equipo bien configurado rinde más y falla menos. Documentamos accesos, respaldos y parámetros para que todo quede bajo control.",
   feats=[("gear", "Buenas prácticas"), ("shield", "Seguridad desde el inicio"), ("activity", "Pruebas completas"), ("file", "Documentación")],
   includes=[("network", "Redes y seguridad", "VLAN, Wi-Fi, firewalls, VPN y políticas de acceso."),
             ("video", "Videovigilancia", "Grabación, analíticos, usuarios y acceso remoto."),
             ("server", "Servidores y equipos", "Sistemas operativos, respaldos, usuarios y actualizaciones."),
             ("activity", "Pruebas de operación", "Validamos cada función contigo antes de entregar.")],
   benefits=[("zap", "Mejor rendimiento", "Equipos ajustados a tu operación real."),
             ("shield", "Más seguridad", "Contraseñas, firmware y accesos bien administrados."),
             ("refresh", "Menos fallas", "Configuraciones estables y probadas."),
             ("file", "Control total", "Documentación clara de accesos y parámetros.")],
   kw="configuración de redes, configuración de NVR, puesta en marcha firewall"),
 dict(slug="soporte-tecnico", name="Soporte técnico", icon="headset", img="soporte",
   short="Atención para resolver dudas, incidencias y requerimientos técnicos.",
   h1=("Soporte técnico", "cuando más lo necesitas"), eyebrow="Remoto · En sitio · Pólizas",
   lead="Resolvemos incidencias de forma remota o en sitio para que tu operación vuelva a la normalidad lo antes posible.",
   sub="Atención técnica cercana, con seguimiento de cada caso.",
   intro="Registramos cada solicitud, te mantenemos informado y damos seguimiento hasta que el problema queda resuelto.",
   feats=[("headset", "Atención directa"), ("clock", "Respuesta ágil"), ("globe", "Remoto o en sitio"), ("file", "Seguimiento")],
   includes=[("headset", "Mesa de ayuda", "Recibimos tus reportes por teléfono, correo o WhatsApp."),
             ("globe", "Soporte remoto", "Diagnóstico y solución a distancia cuando es posible."),
             ("truck", "Visitas en sitio", "Técnicos en tus instalaciones cuando se requiere."),
             ("file", "Pólizas de soporte", "Horas o eventos incluidos con tiempos de respuesta definidos.")],
   benefits=[("clock", "Menos tiempo muerto", "Recupera la operación rápidamente."),
             ("users", "Un solo contacto", "Un equipo que conoce tu infraestructura."),
             ("file", "Historial de casos", "Sabes qué pasó y cómo se resolvió."),
             ("dollar", "Costos previsibles", "Pólizas a la medida de tu operación.")],
   kw="soporte técnico empresas Monterrey, póliza de soporte, soporte redes y CCTV"),
 dict(slug="mantenimiento", name="Mantenimiento", icon="shield", img="mantenimiento",
   short="Servicios preventivos y correctivos para mantener tus soluciones en operación.",
   h1=("Mantenimiento que mantiene", "tu operación en marcha"), eyebrow="Preventivo · Correctivo · Planes",
   lead="Previene fallas, asegura la continuidad de tu operación y maximiza la vida útil de tu infraestructura tecnológica.",
   sub="Equipos siempre funcionando, menos costos inesperados.",
   intro="Programamos visitas periódicas, revisamos cada equipo y te entregamos un reporte con hallazgos y recomendaciones.",
   feats=[("refresh", "Equipos funcionando"), ("dollar", "Menos costos inesperados"), ("clock", "Mayor vida útil"), ("file", "Reportes claros")],
   includes=[("file-search", "Revisión y diagnóstico", "Inspección periódica del estado de cada equipo."),
             ("wrench", "Limpieza y ajuste", "Limpieza, reapriete y alineación de cámaras y equipos."),
             ("refresh", "Actualizaciones", "Firmware y software al día para mayor seguridad."),
             ("file", "Reportes y recomendaciones", "Hallazgos, evidencia y próximos pasos.")],
   benefits=[("shield", "Menor riesgo de fallas", "Detectamos problemas antes de que te detengan."),
             ("refresh", "Operación continua", "Tus sistemas disponibles cuando los necesitas."),
             ("dollar", "Mejor inversión", "Tus equipos duran más y rinden mejor."),
             ("cal", "Planes a la medida", "Frecuencia y alcance según tu operación.")],
   kw="mantenimiento CCTV Monterrey, mantenimiento preventivo redes, mantenimiento UPS"),
 dict(slug="capacitacion", name="Capacitación", icon="users", img="capacitacion",
   short="Acompañamiento para que tu equipo conozca el uso y aprovechamiento de la solución.",
   h1=("Capacitación para aprovechar", "al máximo tu tecnología"), eyebrow="Usuarios · Administradores · Operadores",
   lead="Enseñamos a tu equipo a operar y administrar la solución instalada, con material de apoyo y sesiones prácticas.",
   sub="Formación práctica para usuarios y administradores.",
   intro="Adaptamos cada sesión al perfil de tu equipo: operadores de monitoreo, administradores de red o usuarios finales.",
   feats=[("grad", "Sesiones prácticas"), ("users", "Por perfil"), ("file", "Material de apoyo"), ("headset", "Dudas resueltas")],
   includes=[("grad", "Capacitación de operación", "Uso diario de la plataforma: búsquedas, exportación de video, altas de usuarios."),
             ("gear", "Capacitación de administración", "Configuración, respaldos y buenas prácticas de seguridad."),
             ("file", "Manuales y guías", "Material de consulta adaptado a tu instalación."),
             ("headset", "Seguimiento", "Resolvemos dudas después de la capacitación.")],
   benefits=[("trend", "Más aprovechamiento", "Tu equipo usa todas las funciones que pagaste."),
             ("refresh", "Menos errores", "Operación correcta desde el primer día."),
             ("users", "Autonomía", "Menos dependencia de soporte externo."),
             ("shield", "Más seguridad", "Buenas prácticas en el manejo de accesos.")],
   kw="capacitación videovigilancia, capacitación redes, curso operador CCTV"),
]
SRV = {s["slug"]: s for s in SERVICES}

ARTICLES = [
 dict(slug="como-elegir-la-camara-de-seguridad-ideal", cat="guias", catn="Guía", title="¿Cómo elegir la cámara de seguridad ideal?", date="2026-08-12", read=7,
      desc="Los factores clave para elegir el sistema de videovigilancia que mejor se adapta a tu empresa: lugar, resolución, tipo de cámara y funciones.", img="camara-seguridad", featured=True, full=True),
 dict(slug="ventajas-del-cableado-estructurado", cat="comparativas", catn="Comparativa", title="Ventajas del cableado estructurado en tu empresa", date="2026-08-05", read=6,
      desc="Por qué un cableado bien diseñado mejora el rendimiento, la seguridad y la escalabilidad de tu red.", img="cableado-estructurado", featured=True),
 dict(slug="por-que-necesitas-un-ups", cat="consejos", catn="Consejo técnico", title="¿Por qué necesitas un UPS en tu negocio?", date="2026-07-28", read=5,
      desc="Evita pérdidas, protege tus equipos y garantiza la continuidad de tu operación con un respaldo de energía.", img="ups-negocio", featured=True),
 dict(slug="que-es-poe", cat="tutoriales", catn="Tutorial", title="¿Qué es PoE y cuáles son sus ventajas?", date="2026-08-20", read=5,
      desc="Cómo Power over Ethernet simplifica la instalación de cámaras, teléfonos y puntos de acceso.", img="poe"),
 dict(slug="buenas-practicas-videovigilancia", cat="guias", catn="Guía", title="Buenas prácticas para un sistema de videovigilancia", date="2026-08-15", read=6,
      desc="Consejos clave para maximizar la seguridad y el aprovechamiento de tus cámaras.", img="buenas-practicas-cctv"),
 dict(slug="fibra-optica-vs-cobre", cat="consejos", catn="Consejo técnico", title="Fibra óptica vs. cobre: ¿cuál elegir?", date="2026-08-10", read=6,
      desc="Comparamos ventajas, costos y escenarios de uso para que elijas el medio adecuado.", img="fibra-vs-cobre"),
 dict(slug="control-de-acceso-caso-real", cat="casos", catn="Caso de uso", title="Control de acceso en empresas: un caso real", date="2026-08-02", read=4,
      desc="Cómo un corporativo mejoró su seguridad y eficiencia con control de acceso integrado.", img="caso-control-acceso"),
 dict(slug="nube-vs-almacenamiento-local", cat="comparativas", catn="Comparativa", title="Almacenamiento en la nube vs. almacenamiento local", date="2026-07-28", read=6,
      desc="Diferencias, beneficios y recomendaciones según tu operación.", img="nube-vs-local"),
 dict(slug="tendencias-tecnologicas-2026", cat="novedades", catn="Novedad", title="Tendencias tecnológicas para empresas en 2026", date="2026-07-22", read=5,
      desc="Las tecnologías que están transformando la seguridad y la operación de los negocios.", img="tendencias-2026"),
 dict(slug="camaras-ip-vs-analogicas", cat="comparativas", catn="Comparativa", title="Cámaras IP vs. analógicas: ¿cuál te conviene?", date="2026-07-15", read=6,
      desc="Te ayudamos a entender las diferencias para tomar la mejor decisión.", img="ip-vs-analogicas"),
 dict(slug="como-elegir-un-switch", cat="guias", catn="Guía", title="Cómo elegir un switch para tu red empresarial", date="2026-07-08", read=6,
      desc="Puertos, PoE, capa 2 o 3 y administración: lo que debes revisar antes de comprar.", img="switch-empresarial"),
 dict(slug="nvr-vs-dvr", cat="comparativas", catn="Comparativa", title="Grabadores NVR vs. DVR: ¿cuál elegir?", date="2026-07-01", read=5,
      desc="Conoce las diferencias y aplicaciones de cada tecnología.", img="nvr-vs-dvr"),
]
ART_CATS = [("guias", "Guías", "file", "Aprende paso a paso con nuestros expertos."),
            ("tutoriales", "Tutoriales", "play", "Videos y guías prácticas para tu operación."),
            ("comparativas", "Comparativas", "scale", "Analiza opciones y toma la mejor decisión."),
            ("consejos", "Consejos técnicos", "gear", "Recomendaciones de nuestros especialistas."),
            ("novedades", "Novedades", "bell", "Entérate de las tendencias del sector."),
            ("casos", "Casos de uso", "users", "Historias reales de éxito.")]

MESES = ["", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
MESES_L = ["", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
def fdate(d, long=False):
    y, m, dd = d.split("-")
    return f"{int(dd)} de {MESES_L[int(m)]} de {y}" if long else f"{dd} {MESES[int(m)].upper()} {y}"

FAQ = [
 ("truck", "¿Hacen envíos a toda la República?", "Sí. Enviamos productos a todo México y atendemos proyectos de instalación en distintas ciudades según el alcance."),
 ("box", "¿Puedo solicitar una cotización sin compromiso?", "Por supuesto. Cuéntanos tu necesidad y un asesor te enviará una propuesta sin costo ni compromiso."),
 ("headset", "¿Tienen soporte técnico?", "Sí. Te acompañamos en la implementación y ofrecemos soporte remoto, en sitio y pólizas a la medida."),
 ("clock", "¿En cuánto tiempo responden?", "Respondemos las solicitudes en menos de 24 horas hábiles. Por WhatsApp la atención suele ser inmediata en horario laboral."),
 ("award", "¿Los productos tienen garantía?", "Trabajamos con productos originales de fabricantes líderes, con la garantía oficial de cada marca."),
 ("file", "¿Puedo enviar planos o una lista de materiales?", "Sí. Adjunta tus archivos en el formulario de cotización (PDF, Excel, imágenes o DWG de hasta 10 MB) para agilizar la revisión."),
]
