# -*- coding: utf-8 -*-
"""Contenido del sitio. Edita textos aquí y vuelve a correr build.py."""

CATS = [  # categorías de marcas (una por solución)
    ("videovigilancia", "Videovigilancia y seguridad"), ("acceso", "Control de acceso"),
    ("redes", "Redes y telecom"), ("cableado", "Cableado e infraestructura"), ("energia", "Energía y respaldo"),
    ("ciberseguridad", "Ciberseguridad"), ("computo", "Cómputo y TI"), ("audio-video", "Audio y video"),
]
# Cada categoría corresponde a una solución
CAT_SOL = {"videovigilancia": "videovigilancia", "acceso": "control-de-acceso", "redes": "redes-y-telecomunicaciones",
           "cableado": "cableado-fibra-e-infraestructura", "energia": "energia-y-respaldo", "ciberseguridad": "ciberseguridad",
           "computo": "computo-y-ti", "audio-video": "audio-video-y-colaboracion"}

# Marcas: (nombre, slug, categorías, descripción, frase corta)
# El logo va en assets/img/marcas/<slug>.png
_B = [
 ("AccessPro", "accesspro", "acceso", "Lectores, controladores, cerraduras electromagnéticas y accesorios para sistemas de control de acceso comerciales.", "Control de acceso confiable para puertas y áreas restringidas."),
 ("Altronix", "altronix", "energia videovigilancia acceso", "Fuentes de poder, soluciones PoE y distribución de energía para sistemas de videovigilancia y control de acceso.", "Energía confiable para sistemas de seguridad."),
 ("APC", "apc", "energia", "UPS, protección eléctrica y soluciones de energía de Schneider Electric para mantener la continuidad de la operación.", "Respaldo de energía para que tu operación no se detenga."),
 ("Apple", "apple", "computo", "Computadoras, laptops, tabletas y dispositivos para empresas que buscan productividad, diseño y seguridad.", "Equipos para equipos creativos y productivos."),
 ("ASUS", "asus", "computo", "Laptops, computadoras de escritorio, monitores y equipos de red para oficinas y usuarios profesionales.", "Cómputo confiable para cada puesto de trabajo."),
 ("Belden", "belden", "cableado redes", "Cable de cobre y fibra óptica, conectividad y soluciones de red para entornos empresariales e industriales.", "Conectividad robusta para entornos exigentes."),
 ("Cambium Networks", "cambium-networks", "redes", "Enlaces inalámbricos punto a punto y punto multipunto, Wi-Fi y switching para conectar sitios y sucursales.", "Conectividad inalámbrica de largo alcance."),
 ("CAME", "came", "acceso", "Automatización de accesos: barreras vehiculares, motores para portones, torniquetes y control de acceso.", "Automatización y control de accesos vehiculares y peatonales."),
 ("CDP", "cdp", "energia", "UPS, reguladores y protección eléctrica para hogares, oficinas y empresas.", "Reguladores y UPS para oficinas y comercios."),
 ("Charofil", "charofil", "cableado", "Charola tipo malla y accesorios para la canalización ordenada y segura del cableado.", "Canalización ordenada para tu cableado."),
 ("Check Point", "check-point", "ciberseguridad", "Firewalls, protección de red, nube y endpoints para prevenir amenazas en organizaciones de todos los tamaños.", "Prevención de amenazas para tu red."),
 ("Cisco", "cisco", "redes ciberseguridad", "Switches, routers, Wi-Fi, colaboración y seguridad para redes empresariales de alto desempeño.", "Redes empresariales de clase mundial."),
 ("CommScope", "commscope", "cableado", "Soluciones de cableado estructurado, fibra óptica y conectividad para edificios y centros de datos.", "Conectividad de cobre y fibra de alto desempeño."),
 ("Condumex", "condumex", "cableado energia", "Cables eléctricos, de telecomunicaciones y fibra óptica fabricados en México para proyectos de infraestructura.", "Cables confiables para cada instalación."),
 ("CyberPower", "cyberpower", "energia", "UPS y protección eléctrica para equipos de cómputo, redes y videovigilancia.", "Protección eléctrica accesible y confiable."),
 ("Dahua", "dahua", "videovigilancia acceso", "Videovigilancia y seguridad inteligente con amplio portafolio de cámaras, grabadores y control de acceso.", "Videovigilancia inteligente con un portafolio completo."),
 ("Dell", "dell", "computo", "Computadoras, estaciones de trabajo, servidores y almacenamiento empresarial con soporte y garantía de fabricante.", "Cómputo y servidores empresariales con respaldo de fabricante."),
 ("DJI Enterprise", "dji-enterprise", "videovigilancia", "Drones profesionales para inspección, seguridad, monitoreo y levantamientos en sitios industriales y obras.", "Drones para inspección y seguridad."),
 ("DSC", "dsc", "videovigilancia", "Paneles de alarma, sensores y comunicadores para detección de intrusión en negocios y residencias.", "Alarmas profesionales para proteger tus instalaciones."),
 ("Eaton", "eaton", "energia", "UPS, PDU y administración de energía para centros de datos, oficinas e industria.", "Gestión de energía para infraestructura crítica."),
 ("Elo", "elo", "computo audio-video", "Pantallas táctiles, terminales de punto de venta y kioscos interactivos para comercios y atención al cliente.", "Pantallas táctiles para punto de venta y autoservicio."),
 ("Enson", "enson", "audio-video cableado", "Cables, conectores y accesorios de audio, video y energía para instalaciones y equipos tecnológicos.", "Accesorios y conectividad para tus equipos."),
 ("Epcom", "epcom", "videovigilancia energia cableado", "Portafolio para integradores: cámaras, fuentes de poder, cableado, accesorios y soluciones de energía.", "Accesorios, energía y conectividad para proyectos de seguridad."),
 ("Epson", "epson", "computo audio-video", "Impresoras empresariales, proyectores y escáneres para oficinas, aulas y salas de capacitación.", "Impresión y proyección para oficinas y aulas."),
 ("FAAC", "faac", "acceso", "Automatización de puertas, portones y barreras vehiculares para accesos residenciales, comerciales e industriales.", "Automatización de accesos vehiculares."),
 ("Fanvil", "fanvil", "redes audio-video", "Teléfonos IP, intercomunicadores y dispositivos de comunicación para empresas.", "Telefonía IP e intercomunicación para tu empresa."),
 ("FiberHome", "fiberhome", "redes cableado", "Fibra óptica, equipos de transmisión y soluciones GPON para redes de telecomunicaciones.", "Fibra óptica y redes de acceso."),
 ("Fibrain", "fibrain", "cableado", "Cables y componentes de fibra óptica para redes empresariales, centros de datos y telecomunicaciones.", "Fibra óptica para redes de alto desempeño."),
 ("Fluke Networks", "fluke", "cableado", "Equipos de prueba y certificación de cableado de cobre y fibra óptica.", "Certificación de cableado con precisión."),
 ("Fortinet", "fortinet", "ciberseguridad redes", "Firewalls de nueva generación FortiGate, redes seguras y protección integral de la infraestructura.", "Firewalls y ciberseguridad para proteger la red de tu empresa."),
 ("Grandstream", "grandstream", "redes audio-video", "Telefonía IP, conmutadores, videoconferencia y redes para pequeñas y medianas empresas.", "Comunicaciones unificadas para tu empresa."),
 ("Hanwha Vision", "hanwha", "videovigilancia", "Cámaras, grabadores y analíticos de video Wisenet para proyectos de videovigilancia profesional.", "Videovigilancia profesional con analítica avanzada."),
 ("HID", "hid", "acceso", "Lectores, credenciales, impresoras de identificaciones y soluciones de identidad segura.", "Identidad y control de acceso seguro."),
 ("Hikvision", "hikvision", "videovigilancia acceso", "Fabricante global de videovigilancia, analítica con inteligencia artificial y seguridad electrónica.", "Videovigilancia con tecnología de clase mundial."),
 ("HiRef", "hiref", "cableado energia", "Climatización de precisión para centros de datos, sites y salas de telecomunicaciones.", "Climatización de precisión para tu site."),
 ("nVent Hoffman", "hoffman", "cableado", "Gabinetes, envolventes y gestión térmica para proteger equipos eléctricos y electrónicos.", "Gabinetes para proteger tus equipos."),
 ("Honeywell", "honeywell", "videovigilancia acceso", "Seguridad electrónica, detección de intrusión, videovigilancia y control de acceso.", "Seguridad integral para tus instalaciones."),
 ("HP", "hp", "computo", "Computadoras, laptops, impresoras y periféricos para oficinas y empresas.", "Cómputo e impresión para tu empresa."),
 ("HPE Aruba", "hpe-aruba", "redes", "Redes empresariales cableadas e inalámbricas de alto desempeño, con seguridad integrada y administración en la nube.", "Redes de alto desempeño para campus y oficinas."),
 ("HPE", "hpe", "computo", "Servidores, almacenamiento e infraestructura híbrida para centros de datos y aplicaciones críticas.", "Servidores e infraestructura empresarial."),
 ("Huawei", "huawei", "redes computo audio-video", "Redes empresariales, Wi-Fi, almacenamiento y soluciones de colaboración para organizaciones.", "Tecnología para redes y colaboración."),
 ("IDEMIA", "idemia", "acceso", "Biometría e identidad: lectores faciales y de huella para control de acceso de alta seguridad.", "Biometría de alta seguridad."),
 ("Intellinet", "intellinet", "redes cableado", "Switches, cableado, patch cords y accesorios de conectividad para redes empresariales.", "Conectividad práctica para tu red."),
 ("Kaspersky", "kaspersky", "ciberseguridad", "Protección de endpoints, servidores y correo contra malware y ransomware, con administración centralizada.", "Protección para equipos y servidores."),
 ("Kingston", "kingston", "computo", "Memorias RAM, unidades SSD y almacenamiento flash para mejorar el rendimiento de equipos y servidores.", "Memorias y SSD para más rendimiento."),
 ("LAPP", "lapp", "cableado energia", "Cables y conectividad industrial para automatización, maquinaria y control.", "Cables industriales de alta calidad."),
 ("Lenovo", "lenovo", "computo", "Laptops, equipos de escritorio, estaciones de trabajo y servidores para empresas.", "Equipos de cómputo confiables para cada puesto de trabajo."),
 ("LinkedPro", "linkedpro", "cableado redes", "Cableado, fibra óptica, racks y accesorios de conectividad para redes y videovigilancia.", "Cableado y conectividad para tus proyectos."),
 ("Microsoft", "microsoft", "computo ciberseguridad audio-video", "Licenciamiento de Windows, Microsoft 365, Teams y soluciones de productividad y seguridad en la nube.", "Software de productividad y colaboración."),
 ("MikroTik", "mikrotik", "redes", "Routers, switches y enlaces inalámbricos con gran flexibilidad de configuración.", "Routing y enlaces inalámbricos flexibles."),
 ("Motorola", "motorola", "redes", "Radios de comunicación bidireccional y soluciones de comunicación para equipos de trabajo.", "Radiocomunicación para equipos de trabajo."),
 ("Multilink", "multilink", "cableado", "Gabinetes, fibra óptica y accesorios para redes de telecomunicaciones en interior y exterior.", "Infraestructura para redes de telecomunicaciones."),
 ("Optronics", "optronics", "cableado", "Cables, conectores, distribuidores y accesorios de fibra óptica para redes y enlaces.", "Fibra óptica para tus enlaces."),
 ("Panduit", "panduit", "cableado", "Cableado estructurado de cobre y fibra, organización de racks e infraestructura física para centros de datos.", "Cableado estructurado de alto desempeño."),
 ("PLANET", "planet", "redes", "Switches administrables, PoE e industriales, y equipos de red para empresas y videovigilancia.", "Switches y PoE para redes profesionales."),
 ("QNAP", "qnap", "computo videovigilancia", "Almacenamiento NAS para respaldos, archivos compartidos, virtualización y videovigilancia.", "Almacenamiento NAS para tu información."),
 ("Rittal", "rittal", "cableado energia", "Gabinetes, racks y sistemas de climatización para infraestructura de TI y aplicaciones industriales.", "Racks y gabinetes para proteger tus equipos."),
 ("Rosslare", "rosslare", "acceso", "Controladores, lectores y software de control de acceso para proyectos comerciales y corporativos.", "Control de acceso para empresas."),
 ("Ruijie", "ruijie", "redes", "Switches, Wi-Fi y redes administradas en la nube para empresas, escuelas y hoteles.", "Redes empresariales administradas en la nube."),
 ("SanDisk", "sandisk", "computo", "Memorias, unidades flash y SSD para almacenamiento y transferencia de información.", "Almacenamiento flash confiable."),
 ("Seagate", "seagate", "computo videovigilancia", "Discos duros para videovigilancia (SkyHawk), NAS (IronWolf) y almacenamiento empresarial de alta capacidad.", "Discos de alta capacidad para grabación continua."),
 ("Seco-Larm", "secolarm", "acceso videovigilancia", "Cerraduras electromagnéticas, botones, sensores y accesorios para control de acceso y seguridad.", "Accesorios para control de acceso y seguridad."),
 ("Siemon", "siemon", "cableado", "Cableado estructurado de cobre y fibra, y soluciones para centros de datos.", "Cableado de alto desempeño."),
 ("Streamax", "streamax", "videovigilancia", "Videovigilancia móvil y telemática para flotillas: DVR móviles, cámaras y asistencia a la conducción.", "Video y seguridad para flotillas."),
 ("Suprema", "suprema", "acceso", "Lectores biométricos de rostro y huella, y plataformas de control de acceso y asistencia.", "Biometría para control de acceso y asistencia."),
 ("Synology", "synology", "computo videovigilancia", "NAS para respaldos, archivos compartidos, colaboración y videovigilancia.", "Almacenamiento y respaldo para tu empresa."),
 ("Teltonika", "teltonika", "redes", "Routers y gateways industriales 4G/5G para conectividad remota e IoT.", "Conectividad celular industrial."),
 ("Thorsman", "thorsman", "cableado energia", "Canaletas, ductos y accesorios para la canalización eléctrica y de datos.", "Canalización eléctrica y de datos."),
 ("Total Ground", "total-ground", "energia", "Sistemas de tierra física, pararrayos y protección contra descargas para instalaciones eléctricas.", "Tierras físicas y protección contra descargas."),
 ("TP-Link", "tp-link", "redes videovigilancia", "Switches, puntos de acceso, routers y la línea Omada de administración en la nube.", "Conectividad confiable con excelente relación costo-beneficio."),
 ("Ubiquiti", "ubiquiti", "redes videovigilancia", "Equipos de red empresarial con administración centralizada: Wi-Fi, switching, enlaces y videovigilancia UniFi.", "Redes empresariales administradas de forma centralizada."),
 ("Uniview", "unv", "videovigilancia", "Cámaras IP, grabadores y plataformas de videovigilancia para proyectos de todos los tamaños.", "Videovigilancia IP profesional."),
 ("Velcro", "velcro", "cableado", "Cinchos y amarres reutilizables para organizar y mantener ordenado el cableado.", "Organización práctica del cableado."),
 ("Viakon", "viakon", "cableado energia", "Cables eléctricos y de telecomunicaciones de Conductores Monterrey para instalaciones residenciales e industriales.", "Cables eléctricos hechos en México."),
 ("Western Digital", "western-digital", "computo videovigilancia", "Discos duros y almacenamiento para videovigilancia, NAS y centros de datos, incluidas las líneas WD Purple y WD Red.", "Almacenamiento especializado para videovigilancia y datos."),
 ("Yonusa", "yonusa", "videovigilancia", "Energizadores y accesorios para cercas eléctricas perimetrales.", "Protección perimetral con cercas eléctricas."),
 ("Zebra", "zebra", "computo", "Impresoras de etiquetas, lectores de códigos y computadoras móviles para logística, almacén y punto de venta.", "Identificación y movilidad para tu operación."),
 ("ZKTeco", "zkteco", "acceso videovigilancia", "Biométricos, control de acceso, asistencia, torniquetes y cerraduras inteligentes.", "Control de acceso y asistencia biométrica."),
]
BRANDS = [dict(name=n, slug=sl, cats=c, desc=d, lead=l, sols=[CAT_SOL[k] for k in c.split()]) for n, sl, c, d, l in _B]
BRAND = {b["slug"]: b for b in BRANDS}

# Marcas que aparecen en los carruseles (en este orden). Puedes agregar o quitar slugs.
MARQUEE = ["hikvision", "dahua", "ubiquiti", "tp-link", "fortinet", "cisco", "hpe-aruba", "panduit", "commscope",
           "apc", "eaton", "dell", "hp", "lenovo", "zkteco", "hid", "western-digital", "epson"]

# Líneas de producto y aplicaciones por categoría (para las páginas de marca).
# Para una marca en particular puedes agregar lines=[...] y apps=[...] en su dict.
LINES_BY_CAT = {
    "videovigilancia": [("cctv", "Cámaras IP y analógicas"), ("server", "Grabadores NVR / DVR"), ("bell", "Alarmas e intrusión")],
    "acceso": [("key", "Lectores y biometría"), ("card", "Credenciales e identidad"), ("lock", "Cerraduras y automatización")],
    "redes": [("network", "Switches y routers"), ("wifi", "Wi-Fi y enlaces inalámbricos"), ("phone", "Telefonía IP")],
    "cableado": [("link", "Cableado de cobre"), ("activity", "Fibra óptica"), ("rack", "Racks, gabinetes y canalización")],
    "energia": [("battery", "UPS y baterías"), ("zap", "Regulación y protección"), ("rack", "Distribución de energía")],
    "ciberseguridad": [("shield", "Firewalls"), ("monitor", "Protección de endpoints"), ("lock", "Acceso seguro")],
    "computo": [("monitor", "Equipos de cómputo"), ("server", "Servidores y almacenamiento"), ("printer", "Impresión y periféricos")],
    "audio-video": [("video", "Videoconferencia"), ("monitor", "Pantallas y proyección"), ("sound", "Audio y accesorios")],
}
APPS_BY_CAT = {
    "videovigilancia": ["Oficinas y corporativos", "Comercios y plazas", "Industria y almacenes", "Escuelas"],
    "acceso": ["Accesos de personal", "Fraccionamientos", "Estacionamientos", "Industria"],
    "redes": ["Oficinas", "Naves industriales", "Campus y escuelas", "Hoteles y hospitales"],
    "cableado": ["Centros de datos", "Edificios corporativos", "Naves industriales", "Sites de telecomunicaciones"],
    "energia": ["Sites y centros de datos", "Videovigilancia", "Oficinas", "Industria"],
    "ciberseguridad": ["Oficinas", "Sucursales", "Trabajo remoto", "Centros de datos"],
    "computo": ["Puestos de trabajo", "Áreas de diseño e ingeniería", "Centros de datos", "Punto de venta"],
    "audio-video": ["Salas de juntas", "Capacitación", "Recepciones", "Auditorios"],
}

SOLUTIONS = [
 dict(slug="videovigilancia", name="Videovigilancia y Seguridad Electrónica", icon="cctv",
   short="Soluciones de videovigilancia, monitoreo, grabación, alarmas y seguridad electrónica para proteger instalaciones, personas y activos.",
   card="Seguridad que te da tranquilidad",
   h1=("Videovigilancia para proteger", "lo que más importa"), eyebrow="Videovigilancia · Alarmas · Monitoreo · Seguridad electrónica",
   lead="Soluciones con cámaras IP, grabadores, monitoreo, analíticos y alarmas, diseñadas para empresas y proyectos de cualquier tamaño.",
   intro="Soluciones integrales de videovigilancia y seguridad electrónica para empresas, con tecnología de las mejores marcas y el respaldo de un equipo de expertos.",
   script=("Seguridad que", "te da tranquilidad"),
   feats=[("shield", "Protege tu patrimonio"), ("users", "Mayor control operativo"), ("chart", "Previene incidentes"), ("gear", "Tecnología escalable")],
   includes=[("video", "Cámaras IP", "Modelos para interior y exterior con alta resolución, visión nocturna y WDR."),
             ("db", "Grabación y almacenamiento", "Grabadores NVR/DVR, almacenamiento local o en la nube y respaldo de tu información."),
             ("monitor", "Monitoreo remoto", "Accede a tus cámaras en tiempo real desde computadora, tablet o smartphone."),
             ("bell", "Alarmas e intrusión", "Paneles, sensores, cercas eléctricas y notificaciones ante cualquier evento.")],
   benefits=[("shield", "Más seguridad", "Disuade incidentes y protege a tu personal, instalaciones y activos."),
             ("clock", "Supervisión en tiempo real", "Mantén el control de tus espacios desde cualquier lugar."),
             ("file", "Evidencia y control", "Grabaciones confiables para investigación y cumplimiento."),
             ("chart", "Escalabilidad", "Crece desde un sitio hasta múltiples sucursales.")],
   apps=["Oficinas corporativas", "Comercios y tiendas", "Bodegas y centros de distribución", "Industria y manufactura", "Residenciales y edificios"],
   brands=["hikvision", "dahua", "hanwha", "unv", "ubiquiti", "honeywell", "dsc", "western-digital"],
   cta=("¿Listo para un entorno más seguro?", "Te ayudamos a diseñar la solución de videovigilancia ideal para tu empresa o proyecto."),
   kw="videovigilancia Monterrey, cámaras de seguridad empresas, CCTV, cámaras IP, NVR, alarmas"),
 dict(slug="control-de-acceso", name="Control de Acceso e Identidad", icon="lock",
   short="Soluciones de control de acceso, biometría e identificación para administrar de forma segura el ingreso a instalaciones y áreas restringidas.",
   card="Personas, espacios y mayor seguridad",
   h1=("Control de acceso para", "espacios más seguros"), eyebrow="Biometría · Identificación · Tarjetas · Barreras",
   lead="Controla quién entra, cuándo y por dónde con lectores biométricos, credenciales, torniquetes y barreras vehiculares.",
   intro="Integramos control de acceso, identidad, asistencia y videovigilancia para que administres personas y espacios desde una sola plataforma.",
   script=("Acceso seguro,", "operación fluida"),
   feats=[("key", "Accesos controlados"), ("users", "Registro de personal"), ("shield", "Áreas restringidas"), ("card", "Credenciales y biometría")],
   includes=[("key", "Lectores y biometría", "Huella, rostro, tarjeta o código, en puertas y áreas restringidas."),
             ("card", "Credenciales e identidad", "Tarjetas de proximidad, credenciales móviles e impresión de identificaciones."),
             ("truck", "Accesos vehiculares", "Barreras, lectura de placas y automatización de portones."),
             ("monitor", "Software y reportes", "Horarios, niveles de acceso y reportes de asistencia.")],
   benefits=[("shield", "Mayor seguridad", "Solo las personas autorizadas acceden a cada área."),
             ("clock", "Control de asistencia", "Registros confiables de entradas y salidas."),
             ("file", "Trazabilidad", "Historial de eventos para auditorías e investigaciones."),
             ("gear", "Integración", "Se conecta con videovigilancia y alarmas.")],
   apps=["Corporativos", "Plantas industriales", "Residenciales", "Estacionamientos", "Escuelas"],
   brands=["zkteco", "hid", "suprema", "idemia", "rosslare", "accesspro", "came", "faac"],
   cta=("¿Quieres saber quién entra a tus instalaciones?", "Diseñamos el sistema de control de acceso adecuado para tu operación."),
   kw="control de acceso Monterrey, biométricos, identificación, torniquetes, barreras vehiculares"),
 dict(slug="redes-y-telecomunicaciones", name="Redes y Telecomunicaciones", icon="network",
   short="Soluciones de redes, Wi-Fi, switching, routing, telefonía IP y telecomunicaciones para mantener una conectividad confiable y escalable.",
   card="Conectividad confiable y escalable",
   h1=("Redes y telecomunicaciones para una", "operación siempre conectada"), eyebrow="Wi-Fi · Switching · Routing · Telefonía IP",
   lead="Diseñamos e implementamos redes LAN/WLAN, enlaces inalámbricos y telefonía IP con equipos de nivel empresarial.",
   intro="Redes estables, seguras y administrables, desde una oficina hasta múltiples sucursales conectadas entre sí.",
   script=("Conectividad", "sin límites"),
   feats=[("wifi", "Wi-Fi empresarial"), ("network", "Red administrable"), ("phone", "Telefonía IP"), ("trend", "Lista para crecer")],
   includes=[("wifi", "Redes inalámbricas", "Site survey, puntos de acceso empresariales y roaming sin cortes."),
             ("network", "Switching y routing", "Switches administrables, PoE, VLAN y enrutamiento entre sitios."),
             ("activity", "Enlaces inalámbricos", "Enlaces punto a punto y multipunto entre edificios y sucursales."),
             ("phone", "Telefonía IP", "Conmutadores, teléfonos IP e intercomunicación para tu empresa.")],
   benefits=[("zap", "Mayor velocidad", "Aprovecha al máximo tus aplicaciones y servicios en la nube."),
             ("refresh", "Menos fallas", "Una red bien diseñada es más fácil de mantener y diagnosticar."),
             ("shield", "Más seguridad", "Segmentación de red y control del tráfico para proteger tu información."),
             ("trend", "Escalabilidad", "Infraestructura preparada para nuevos usuarios y sucursales.")],
   apps=["Oficinas corporativas", "Naves industriales", "Escuelas y campus", "Hoteles y hospitales", "Sucursales"],
   brands=["ubiquiti", "tp-link", "hpe-aruba", "cisco", "mikrotik", "ruijie", "cambium-networks", "grandstream"],
   cta=("¿Tu red necesita orden y velocidad?", "Evaluamos tu red y te proponemos la mejor arquitectura."),
   kw="redes empresariales Monterrey, wifi empresarial, switches, telefonía IP, enlaces inalámbricos"),
 dict(slug="cableado-fibra-e-infraestructura", name="Cableado, Fibra e Infraestructura", icon="rack",
   short="Soluciones de cableado estructurado, fibra óptica, racks, gabinetes y canalización para construir una infraestructura confiable y preparada para crecer.",
   card="Infraestructura lista para crecer",
   h1=("Cableado e infraestructura", "que soporta tu operación"), eyebrow="Cableado estructurado · Fibra óptica · Racks · Canalización",
   lead="Cableado de cobre y fibra óptica, racks, gabinetes y canalización instalados con orden, certificación y documentación.",
   intro="La base física de tu red: ordenada, certificada y documentada, lista para soportar el crecimiento de tu empresa.",
   script=("Infraestructura", "que perdura"),
   feats=[("link", "Cableado certificado"), ("activity", "Fibra óptica"), ("rack", "Racks y gabinetes"), ("layers", "Canalización ordenada")],
   includes=[("link", "Cableado estructurado", "Categorías 6 y 6A, certificación de nodos, etiquetado y documentación."),
             ("activity", "Fibra óptica", "Backbones y enlaces entre edificios, fusión y pruebas con reflectómetro."),
             ("rack", "Racks y gabinetes", "Racks, gabinetes, organización de cableado y climatización para sites."),
             ("layers", "Canalización", "Charola, tubería, canaletas y tierras físicas para una instalación segura.")],
   benefits=[("refresh", "Menos fallas", "Una instalación certificada evita fallas intermitentes y pérdidas de señal."),
             ("file", "Documentación", "Planos y etiquetado que facilitan mantenimientos y cambios."),
             ("trend", "Preparada para crecer", "Capacidad para nuevos nodos, equipos y tecnologías."),
             ("award", "Garantía de fabricante", "Sistemas certificados con respaldo de las marcas.")],
   apps=["Oficinas y corporativos", "Centros de datos", "Naves industriales", "Hospitales y escuelas", "Edificios nuevos"],
   brands=["panduit", "commscope", "siemon", "belden", "fibrain", "rittal", "charofil", "fluke"],
   cta=("¿Tu cableado está listo para crecer?", "Diseñamos e instalamos la infraestructura física que tu red necesita."),
   kw="cableado estructurado Monterrey, fibra óptica, racks, gabinetes, canalización, certificación"),
 dict(slug="energia-y-respaldo", name="Energía y Respaldo", icon="zap",
   short="Soluciones de UPS, baterías, protección eléctrica y respaldo de energía para mantener operativa y protegida la infraestructura tecnológica.",
   card="Tu operación siempre en marcha",
   h1=("Energía y respaldo para que", "tu operación no se detenga"), eyebrow="UPS · Baterías · Protección eléctrica",
   lead="UPS, baterías, reguladores, PDU y protección eléctrica dimensionados para tus equipos críticos.",
   intro="Calculamos la carga real de tus equipos para recomendarte el respaldo adecuado, sin quedarte corto ni sobredimensionar.",
   script=("Energía que", "no se detiene"),
   feats=[("battery", "Respaldo continuo"), ("shield", "Equipos protegidos"), ("activity", "Energía estable"), ("refresh", "Continuidad")],
   includes=[("battery", "UPS y baterías", "Equipos interactivos y en línea de doble conversión, desde oficina hasta centro de datos."),
             ("activity", "Regulación y protección", "Reguladores, supresores de picos y tierras físicas."),
             ("rack", "Distribución de energía", "PDU básicas, medidas y administrables para racks."),
             ("monitor", "Monitoreo", "Tarjetas de red y software para apagado seguro y alertas.")],
   benefits=[("refresh", "Continuidad operativa", "Tus sistemas siguen funcionando durante apagones y variaciones."),
             ("shield", "Protección de equipos", "Evita daños por picos, sobretensiones y cortes."),
             ("dollar", "Menos pérdidas", "Reduce tiempos muertos y reparaciones costosas."),
             ("bell", "Alertas oportunas", "Recibe avisos antes de que la batería se agote.")],
   apps=["Centros de datos", "Oficinas", "Videovigilancia", "Puntos de venta", "Industria"],
   brands=["apc", "eaton", "cyberpower", "cdp", "altronix", "total-ground"],
   cta=("¿Qué pasaría si se va la luz hoy?", "Te ayudamos a calcular el respaldo que realmente necesitas."),
   kw="UPS Monterrey, no break empresarial, respaldo de energía, baterías, reguladores"),
 dict(slug="ciberseguridad", name="Ciberseguridad", icon="shield",
   short="Soluciones de seguridad de red, firewalls, protección de endpoints y acceso seguro para fortalecer la infraestructura tecnológica de la organización.",
   card="Protección para tu información",
   h1=("Ciberseguridad para proteger", "tu información y tu operación"), eyebrow="Firewalls · Endpoints · Acceso seguro · Monitoreo",
   lead="Firewalls de nueva generación, protección de equipos, acceso remoto seguro y políticas para reducir riesgos en tu red.",
   intro="Fortalecemos tu infraestructura con capas de protección adecuadas al tamaño de tu empresa y a la información que manejas.",
   script=("Tu información,", "siempre protegida"),
   feats=[("shield", "Red protegida"), ("lock", "Acceso seguro"), ("monitor", "Equipos protegidos"), ("eye", "Visibilidad")],
   includes=[("shield", "Firewalls", "Firewalls de nueva generación con filtrado web, prevención de intrusiones y control de aplicaciones."),
             ("monitor", "Protección de endpoints", "Antivirus y EDR para computadoras y servidores, con administración centralizada."),
             ("lock", "Acceso remoto seguro", "VPN y autenticación para conectar sucursales y personal a distancia."),
             ("eye", "Monitoreo y políticas", "Segmentación, reportes y políticas de uso para detectar y prevenir riesgos.")],
   benefits=[("shield", "Menos riesgos", "Reduce la exposición a malware, ransomware y accesos no autorizados."),
             ("refresh", "Continuidad", "Evita paros por incidentes de seguridad."),
             ("eye", "Visibilidad", "Conoce qué pasa en tu red y quién accede a qué."),
             ("file", "Cumplimiento", "Apoya la protección de datos personales y auditorías.")],
   apps=["Oficinas corporativas", "Sucursales", "Trabajo remoto", "Centros de datos", "Sector salud y educación"],
   brands=["fortinet", "check-point", "kaspersky", "cisco", "microsoft"],
   cta=("¿Qué tan protegida está tu red?", "Revisamos tu infraestructura y te proponemos la protección adecuada."),
   kw="ciberseguridad Monterrey, firewall empresarial, Fortinet, antivirus empresarial, VPN"),
 dict(slug="computo-y-ti", name="Cómputo y TI", icon="monitor",
   short="Soluciones de cómputo, servidores, almacenamiento, impresión y equipamiento TI para impulsar la productividad y operación de las organizaciones.",
   card="Tecnología para trabajar mejor",
   h1=("Cómputo y TI para", "equipos más productivos"), eyebrow="Equipos · Servidores · Almacenamiento · Impresión",
   lead="Computadoras, estaciones de trabajo, servidores, almacenamiento, impresión y licenciamiento para cada área de tu empresa.",
   intro="Te ayudamos a elegir el equipo correcto para cada perfil de usuario y a estandarizar tu infraestructura de TI.",
   script=("Tecnología para", "trabajar mejor"),
   feats=[("monitor", "Equipos por perfil"), ("server", "Servidores"), ("hdd", "Almacenamiento"), ("award", "Garantía de fábrica")],
   includes=[("monitor", "Computadoras y laptops", "Equipos de escritorio, laptops y estaciones de trabajo empresariales."),
             ("server", "Servidores", "Servidores para tus aplicaciones, virtualización y bases de datos."),
             ("hdd", "Almacenamiento", "NAS, discos, SSD y soluciones de respaldo para tu información."),
             ("printer", "Impresión y periféricos", "Impresoras, etiquetadoras, lectores, puntos de venta y accesorios.")],
   benefits=[("trend", "Más productividad", "Equipos adecuados para cada tarea y usuario."),
             ("award", "Garantía de fabricante", "Productos originales con respaldo oficial."),
             ("layers", "Estandarización", "Una infraestructura homogénea es más fácil de administrar."),
             ("truck", "Entrega en todo México", "Logística para oficinas y sucursales.")],
   apps=["Oficinas", "Áreas de diseño e ingeniería", "Centros de datos", "Almacenes y logística", "Escuelas"],
   brands=["dell", "hp", "lenovo", "hpe", "asus", "synology", "qnap", "zebra"],
   cta=("¿Vas a renovar tus equipos?", "Te armamos una propuesta por perfil de usuario y presupuesto."),
   kw="equipo de cómputo empresas Monterrey, laptops empresariales, servidores, NAS, impresión"),
 dict(slug="audio-video-y-colaboracion", name="Audio, Video y Colaboración", icon="video",
   short="Soluciones de videoconferencia, pantallas interactivas, proyección, distribución de audio y video y herramientas de colaboración para mejorar la comunicación y presentación de contenidos.",
   card="Comunicación sin distancias",
   h1=("Audio, video y colaboración para", "comunicarte mejor"), eyebrow="Videoconferencia · Pantallas · Proyección · Audio",
   lead="Salas de juntas, videoconferencia, pantallas interactivas, proyección y distribución de audio y video para tu empresa.",
   intro="Equipamos salas y espacios para que tus reuniones, presentaciones y capacitaciones sean claras, sencillas y profesionales.",
   script=("Reuniones que", "sí conectan"),
   feats=[("video", "Videoconferencia"), ("monitor", "Pantallas interactivas"), ("sound", "Audio claro"), ("users", "Colaboración")],
   includes=[("video", "Videoconferencia", "Cámaras, barras de video y micrófonos para salas pequeñas, medianas y grandes."),
             ("monitor", "Pantallas e interactivos", "Pantallas profesionales, pizarrones interactivos y señalización digital."),
             ("play", "Proyección", "Proyectores y pantallas para auditorios, aulas y salas de capacitación."),
             ("sound", "Audio y distribución", "Audio ambiental, voceo y distribución de audio y video entre espacios.")],
   benefits=[("users", "Mejor colaboración", "Reuniones fluidas entre oficinas, sucursales y personal remoto."),
             ("clock", "Menos tiempo perdido", "Salas listas para usarse con un solo clic."),
             ("eye", "Presentaciones claras", "Imagen y audio de calidad para cualquier audiencia."),
             ("layers", "Espacios estandarizados", "La misma experiencia en todas tus salas.")],
   apps=["Salas de juntas", "Aulas y capacitación", "Auditorios", "Recepciones", "Centros de monitoreo"],
   brands=["epson", "elo", "grandstream", "huawei", "microsoft", "enson"],
   cta=("¿Tus reuniones necesitan mejor imagen y sonido?", "Diseñamos la sala ideal para tu forma de trabajar."),
   kw="videoconferencia Monterrey, salas de juntas, pantallas interactivas, proyectores, audio profesional"),
]
SOL = {s["slug"]: s for s in SOLUTIONS}

SERVICES = [
 dict(slug="asesoria-especializada", name="Asesoría especializada", icon="user", img="asesoria",
   short="Te orientamos para encontrar la solución adecuada según tus necesidades y presupuesto.",
   h1=("Asesoría especializada", "para encontrar la solución ideal"), eyebrow="Asesoría · Planeación · Tecnología",
   lead="Entendemos las necesidades de tu negocio y te orientamos con la mejor tecnología para que tomes decisiones seguras y alineadas a tus objetivos.",
   sub="Un servicio experto para convertir tus necesidades en soluciones tecnológicas de alto valor.",
   intro="Te acompañamos desde la idea hasta la implementación, analizando tus necesidades, recomendando la tecnología y diseñando una solución a la medida.",
   feats=[("shield", "Proyectos más seguros"), ("users", "Expertos a tu lado"), ("chart", "Tecnología que impulsa"), ("gear", "Resultados reales")],
   includes=[("file-search", "Análisis de necesidades", "Conocemos tu operación, objetivos y desafíos para entender lo que realmente necesitas."),
             ("gear", "Recomendación tecnológica", "Te sugerimos opciones de tecnología, marcas y arquitecturas según tus requerimientos."),
             ("scale", "Evaluación de alternativas", "Comparamos soluciones en costo, funcionalidad y escalabilidad."),
             ("map", "Planeación de solución", "Definimos el plan de implementación, recursos y próximos pasos.")],
   benefits=[("target", "Decisiones fundamentadas", "Con información técnica y análisis experto."),
             ("puzzle", "Solución a la medida", "Tecnología alineada a tus objetivos."),
             ("clock", "Ahorro de tiempo", "Evita pruebas y errores con la guía de especialistas."),
             ("chart", "Mejor inversión", "Maximiza el rendimiento de tu presupuesto.")],
   kw="asesoría tecnológica, consultoría TI Monterrey, diseño de proyectos de seguridad"),
 dict(slug="instalacion", name="Instalación", icon="wrench", img="instalacion",
   short="Implementación física de equipos, cableado e infraestructura tecnológica.",
   h1=("Instalación profesional", "con altos estándares"), eyebrow="Obra · Montaje · Cableado",
   lead="Montamos cámaras, cableado, racks y equipos con técnicos capacitados, cuidando la seguridad, el orden y los tiempos de tu proyecto.",
   sub="Implementación física cuidada, documentada y entregada funcionando.",
   intro="Planeamos la obra contigo, respetamos tus horarios de operación y te entregamos memoria técnica de todo lo instalado.",
   feats=[("shield", "Trabajo seguro"), ("users", "Técnicos certificados"), ("clock", "Tiempos cumplidos"), ("file", "Memoria técnica")],
   includes=[("map", "Levantamiento en sitio", "Visitamos tus instalaciones para definir rutas, alturas y materiales."),
             ("wrench", "Montaje de equipos", "Cámaras, lectores, puntos de acceso, pantallas y racks."),
             ("network", "Canalización y cableado", "Tubería, charola, cableado de cobre y fibra con buenas prácticas."),
             ("file", "Pruebas y entrega", "Certificación, etiquetado y memoria técnica del proyecto.")],
   benefits=[("award", "Calidad de obra", "Instalaciones limpias, ordenadas y duraderas."),
             ("shield", "Seguridad en sitio", "Personal con equipo de protección y protocolos."),
             ("clock", "Menos interrupciones", "Trabajamos en horarios que no afecten tu operación."),
             ("file", "Todo documentado", "Planos y registros para futuros mantenimientos.")],
   kw="instalación de cámaras Monterrey, instalación de cableado estructurado, montaje de racks"),
 dict(slug="configuracion-y-puesta-en-marcha", name="Configuración y puesta en marcha", icon="gear", img="configuracion",
   short="Dejamos tus equipos listos para operar de forma correcta y eficiente.",
   h1=("Configuración y puesta en marcha", "lista para operar"), eyebrow="Configuración · Pruebas · Arranque",
   lead="Configuramos redes, grabadores, firewalls, controles de acceso y servidores con las mejores prácticas de cada fabricante.",
   sub="Tus equipos funcionando desde el primer día, con la configuración correcta.",
   intro="Un equipo bien configurado rinde más y falla menos. Documentamos accesos, respaldos y parámetros para que todo quede bajo control.",
   feats=[("gear", "Buenas prácticas"), ("shield", "Seguridad desde el inicio"), ("activity", "Pruebas completas"), ("file", "Documentación")],
   includes=[("network", "Redes y seguridad", "VLAN, Wi-Fi, firewalls, VPN y políticas de acceso."),
             ("video", "Videovigilancia", "Grabación, analíticos, usuarios y acceso remoto."),
             ("server", "Servidores y equipos", "Sistemas operativos, respaldos, usuarios y actualizaciones."),
             ("activity", "Pruebas de operación", "Validamos cada función contigo antes de entregar.")],
   benefits=[("zap", "Mejor rendimiento", "Equipos ajustados a tu operación real."),
             ("shield", "Más seguridad", "Contraseñas, firmware y accesos bien administrados."),
             ("refresh", "Menos fallas", "Configuraciones estables y probadas."),
             ("file", "Control total", "Documentación clara de accesos y parámetros.")],
   kw="configuración de redes, configuración de NVR, puesta en marcha firewall"),
 dict(slug="soporte-tecnico", name="Soporte técnico", icon="headset", img="soporte",
   short="Atención para resolver dudas, incidencias y requerimientos técnicos.",
   h1=("Soporte técnico", "cuando más lo necesitas"), eyebrow="Remoto · En sitio · Pólizas",
   lead="Resolvemos incidencias de forma remota o en sitio para que tu operación vuelva a la normalidad lo antes posible.",
   sub="Atención técnica cercana, con seguimiento de cada caso.",
   intro="Registramos cada solicitud, te mantenemos informado y damos seguimiento hasta que el problema queda resuelto.",
   feats=[("headset", "Atención directa"), ("clock", "Respuesta ágil"), ("globe", "Remoto o en sitio"), ("file", "Seguimiento")],
   includes=[("headset", "Mesa de ayuda", "Recibimos tus reportes por teléfono, correo o WhatsApp."),
             ("globe", "Soporte remoto", "Diagnóstico y solución a distancia cuando es posible."),
             ("truck", "Visitas en sitio", "Técnicos en tus instalaciones cuando se requiere."),
             ("file", "Pólizas de soporte", "Horas o eventos incluidos con tiempos de respuesta definidos.")],
   benefits=[("clock", "Menos tiempo muerto", "Recupera la operación rápidamente."),
             ("users", "Un solo contacto", "Un equipo que conoce tu infraestructura."),
             ("file", "Historial de casos", "Sabes qué pasó y cómo se resolvió."),
             ("dollar", "Costos previsibles", "Pólizas a la medida de tu operación.")],
   kw="soporte técnico empresas Monterrey, póliza de soporte, soporte redes y CCTV"),
 dict(slug="mantenimiento", name="Mantenimiento", icon="shield", img="mantenimiento",
   short="Servicios preventivos y correctivos para mantener tus soluciones en operación.",
   h1=("Mantenimiento que mantiene", "tu operación en marcha"), eyebrow="Preventivo · Correctivo · Planes",
   lead="Previene fallas, asegura la continuidad de tu operación y maximiza la vida útil de tu infraestructura tecnológica.",
   sub="Equipos siempre funcionando, menos costos inesperados.",
   intro="Programamos visitas periódicas, revisamos cada equipo y te entregamos un reporte con hallazgos y recomendaciones.",
   feats=[("refresh", "Equipos funcionando"), ("dollar", "Menos costos inesperados"), ("clock", "Mayor vida útil"), ("file", "Reportes claros")],
   includes=[("file-search", "Revisión y diagnóstico", "Inspección periódica del estado de cada equipo."),
             ("wrench", "Limpieza y ajuste", "Limpieza, reapriete y alineación de cámaras y equipos."),
             ("refresh", "Actualizaciones", "Firmware y software al día para mayor seguridad."),
             ("file", "Reportes y recomendaciones", "Hallazgos, evidencia y próximos pasos.")],
   benefits=[("shield", "Menor riesgo de fallas", "Detectamos problemas antes de que te detengan."),
             ("refresh", "Operación continua", "Tus sistemas disponibles cuando los necesitas."),
             ("dollar", "Mejor inversión", "Tus equipos duran más y rinden mejor."),
             ("cal", "Planes a la medida", "Frecuencia y alcance según tu operación.")],
   kw="mantenimiento CCTV Monterrey, mantenimiento preventivo redes, mantenimiento UPS"),
 dict(slug="capacitacion", name="Capacitación", icon="users", img="capacitacion",
   short="Acompañamiento para que tu equipo conozca el uso y aprovechamiento de la solución.",
   h1=("Capacitación para aprovechar", "al máximo tu tecnología"), eyebrow="Usuarios · Administradores · Operadores",
   lead="Enseñamos a tu equipo a operar y administrar la solución instalada, con material de apoyo y sesiones prácticas.",
   sub="Formación práctica para usuarios y administradores.",
   intro="Adaptamos cada sesión al perfil de tu equipo: operadores de monitoreo, administradores de red o usuarios finales.",
   feats=[("grad", "Sesiones prácticas"), ("users", "Por perfil"), ("file", "Material de apoyo"), ("headset", "Dudas resueltas")],
   includes=[("grad", "Capacitación de operación", "Uso diario de la plataforma: búsquedas, exportación de video, altas de usuarios."),
             ("gear", "Capacitación de administración", "Configuración, respaldos y buenas prácticas de seguridad."),
             ("file", "Manuales y guías", "Material de consulta adaptado a tu instalación."),
             ("headset", "Seguimiento", "Resolvemos dudas después de la capacitación.")],
   benefits=[("trend", "Más aprovechamiento", "Tu equipo usa todas las funciones que pagaste."),
             ("refresh", "Menos errores", "Operación correcta desde el primer día."),
             ("users", "Autonomía", "Menos dependencia de soporte externo."),
             ("shield", "Más seguridad", "Buenas prácticas en el manejo de accesos.")],
   kw="capacitación videovigilancia, capacitación redes, curso operador CCTV"),
]
SRV = {s["slug"]: s for s in SERVICES}

ARTICLES = [
 dict(slug="como-elegir-la-camara-de-seguridad-ideal", cat="guias", catn="Guía", title="¿Cómo elegir la cámara de seguridad ideal?", date="2026-08-12", read=7,
      desc="Los factores clave para elegir el sistema de videovigilancia que mejor se adapta a tu empresa: lugar, resolución, tipo de cámara y funciones.", img="camara-seguridad", featured=True, full=True),
 dict(slug="ventajas-del-cableado-estructurado", cat="comparativas", catn="Comparativa", title="Ventajas del cableado estructurado en tu empresa", date="2026-08-05", read=6,
      desc="Por qué un cableado bien diseñado mejora el rendimiento, la seguridad y la escalabilidad de tu red.", img="cableado-estructurado", featured=True),
 dict(slug="por-que-necesitas-un-ups", cat="consejos", catn="Consejo técnico", title="¿Por qué necesitas un UPS en tu negocio?", date="2026-07-28", read=5,
      desc="Evita pérdidas, protege tus equipos y garantiza la continuidad de tu operación con un respaldo de energía.", img="ups-negocio", featured=True),
 dict(slug="que-es-poe", cat="tutoriales", catn="Tutorial", title="¿Qué es PoE y cuáles son sus ventajas?", date="2026-08-20", read=5,
      desc="Cómo Power over Ethernet simplifica la instalación de cámaras, teléfonos y puntos de acceso.", img="poe"),
 dict(slug="buenas-practicas-videovigilancia", cat="guias", catn="Guía", title="Buenas prácticas para un sistema de videovigilancia", date="2026-08-15", read=6,
      desc="Consejos clave para maximizar la seguridad y el aprovechamiento de tus cámaras.", img="buenas-practicas-cctv"),
 dict(slug="fibra-optica-vs-cobre", cat="consejos", catn="Consejo técnico", title="Fibra óptica vs. cobre: ¿cuál elegir?", date="2026-08-10", read=6,
      desc="Comparamos ventajas, costos y escenarios de uso para que elijas el medio adecuado.", img="fibra-vs-cobre"),
 dict(slug="control-de-acceso-caso-real", cat="casos", catn="Caso de uso", title="Control de acceso en empresas: un caso real", date="2026-08-02", read=4,
      desc="Cómo un corporativo mejoró su seguridad y eficiencia con control de acceso integrado.", img="caso-control-acceso"),
 dict(slug="nube-vs-almacenamiento-local", cat="comparativas", catn="Comparativa", title="Almacenamiento en la nube vs. almacenamiento local", date="2026-07-28", read=6,
      desc="Diferencias, beneficios y recomendaciones según tu operación.", img="nube-vs-local"),
 dict(slug="tendencias-tecnologicas-2026", cat="novedades", catn="Novedad", title="Tendencias tecnológicas para empresas en 2026", date="2026-07-22", read=5,
      desc="Las tecnologías que están transformando la seguridad y la operación de los negocios.", img="tendencias-2026"),
 dict(slug="camaras-ip-vs-analogicas", cat="comparativas", catn="Comparativa", title="Cámaras IP vs. analógicas: ¿cuál te conviene?", date="2026-07-15", read=6,
      desc="Te ayudamos a entender las diferencias para tomar la mejor decisión.", img="ip-vs-analogicas"),
 dict(slug="como-elegir-un-switch", cat="guias", catn="Guía", title="Cómo elegir un switch para tu red empresarial", date="2026-07-08", read=6,
      desc="Puertos, PoE, capa 2 o 3 y administración: lo que debes revisar antes de comprar.", img="switch-empresarial"),
 dict(slug="nvr-vs-dvr", cat="comparativas", catn="Comparativa", title="Grabadores NVR vs. DVR: ¿cuál elegir?", date="2026-07-01", read=5,
      desc="Conoce las diferencias y aplicaciones de cada tecnología.", img="nvr-vs-dvr"),
]
ART_CATS = [("guias", "Guías", "file", "Aprende paso a paso con nuestros expertos."),
            ("tutoriales", "Tutoriales", "play", "Videos y guías prácticas para tu operación."),
            ("comparativas", "Comparativas", "scale", "Analiza opciones y toma la mejor decisión."),
            ("consejos", "Consejos técnicos", "gear", "Recomendaciones de nuestros especialistas."),
            ("novedades", "Novedades", "bell", "Entérate de las tendencias del sector."),
            ("casos", "Casos de uso", "users", "Historias reales de éxito.")]

MESES = ["", "ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
MESES_L = ["", "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"]
def fdate(d, long=False):
    y, m, dd = d.split("-")
    return f"{int(dd)} de {MESES_L[int(m)]} de {y}" if long else f"{dd} {MESES[int(m)].upper()} {y}"

FAQ = [
 ("truck", "¿Hacen envíos a toda la República?", "Sí. Enviamos productos a todo México y atendemos proyectos de instalación en distintas ciudades según el alcance."),
 ("box", "¿Puedo solicitar una cotización sin compromiso?", "Por supuesto. Cuéntanos tu necesidad y un asesor te enviará una propuesta sin costo ni compromiso."),
 ("headset", "¿Tienen soporte técnico?", "Sí. Te acompañamos en la implementación y ofrecemos soporte remoto, en sitio y pólizas a la medida."),
 ("clock", "¿En cuánto tiempo responden?", "Respondemos las solicitudes en menos de 24 horas hábiles. Por WhatsApp la atención suele ser inmediata en horario laboral."),
 ("award", "¿Los productos tienen garantía?", "Trabajamos con productos originales de fabricantes líderes, con la garantía oficial de cada marca."),
 ("file", "¿Puedo enviar planos o una lista de materiales?", "Sí. Adjunta tus archivos en el formulario de cotización (PDF, Excel, imágenes o DWG de hasta 10 MB) para agilizar la revisión."),
]
